// proto/cyberday.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/cyberday.proto

package cyberday

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Solicitud de registro que incluye ID, Tipo y Direccion de la entidad
type SolicitudRegistro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdEntidad     string                 `protobuf:"bytes,1,opt,name=id_entidad,json=idEntidad,proto3" json:"id_entidad,omitempty"`
	TipoEntidad   string                 `protobuf:"bytes,2,opt,name=tipo_entidad,json=tipoEntidad,proto3" json:"tipo_entidad,omitempty"`
	Direccion     string                 `protobuf:"bytes,3,opt,name=direccion,proto3" json:"direccion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudRegistro) Reset() {
	*x = SolicitudRegistro{}
	mi := &file_proto_cyberday_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudRegistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudRegistro) ProtoMessage() {}

func (x *SolicitudRegistro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudRegistro.ProtoReflect.Descriptor instead.
func (*SolicitudRegistro) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudRegistro) GetIdEntidad() string {
	if x != nil {
		return x.IdEntidad
	}
	return ""
}

func (x *SolicitudRegistro) GetTipoEntidad() string {
	if x != nil {
		return x.TipoEntidad
	}
	return ""
}

func (x *SolicitudRegistro) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

// Resultado del registro
type RespuestaRegistro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaRegistro) Reset() {
	*x = RespuestaRegistro{}
	mi := &file_proto_cyberday_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaRegistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaRegistro) ProtoMessage() {}

func (x *RespuestaRegistro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaRegistro.ProtoReflect.Descriptor instead.
func (*RespuestaRegistro) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{1}
}

func (x *RespuestaRegistro) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RespuestaRegistro) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type SolicitudInicio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudInicio) Reset() {
	*x = SolicitudInicio{}
	mi := &file_proto_cyberday_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudInicio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudInicio) ProtoMessage() {}

func (x *SolicitudInicio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudInicio.ProtoReflect.Descriptor instead.
func (*SolicitudInicio) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{2}
}

type RespuestaInicio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listo         bool                   `protobuf:"varint,1,opt,name=listo,proto3" json:"listo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaInicio) Reset() {
	*x = RespuestaInicio{}
	mi := &file_proto_cyberday_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaInicio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaInicio) ProtoMessage() {}

func (x *RespuestaInicio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaInicio.ProtoReflect.Descriptor instead.
func (*RespuestaInicio) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaInicio) GetListo() bool {
	if x != nil {
		return x.Listo
	}
	return false
}

// Mensaje de oferta que incluye todos los atributos necesarios
type Oferta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfertaId      string                 `protobuf:"bytes,1,opt,name=oferta_id,json=ofertaId,proto3" json:"oferta_id,omitempty"`
	Tienda        string                 `protobuf:"bytes,2,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Categoria     string                 `protobuf:"bytes,3,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Producto      string                 `protobuf:"bytes,4,opt,name=producto,proto3" json:"producto,omitempty"`
	Precio        int64                  `protobuf:"varint,5,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Fecha         string                 `protobuf:"bytes,7,opt,name=fecha,proto3" json:"fecha,omitempty"`
	Descuento     float32                `protobuf:"fixed32,8,opt,name=descuento,proto3" json:"descuento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Oferta) Reset() {
	*x = Oferta{}
	mi := &file_proto_cyberday_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Oferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oferta) ProtoMessage() {}

func (x *Oferta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oferta.ProtoReflect.Descriptor instead.
func (*Oferta) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{4}
}

func (x *Oferta) GetOfertaId() string {
	if x != nil {
		return x.OfertaId
	}
	return ""
}

func (x *Oferta) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Oferta) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Oferta) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Oferta) GetPrecio() int64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Oferta) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Oferta) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *Oferta) GetDescuento() float32 {
	if x != nil {
		return x.Descuento
	}
	return 0
}

// Mensaje que indica si la oferta se escribio exitosamente y tambien un indicador de si el broker sigue recibiendo ofertas
type RespuestaOferta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aceptado      bool                   `protobuf:"varint,1,opt,name=aceptado,proto3" json:"aceptado,omitempty"` // True if W=2
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Termino       bool                   `protobuf:"varint,3,opt,name=termino,proto3" json:"termino,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaOferta) Reset() {
	*x = RespuestaOferta{}
	mi := &file_proto_cyberday_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaOferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaOferta) ProtoMessage() {}

func (x *RespuestaOferta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaOferta.ProtoReflect.Descriptor instead.
func (*RespuestaOferta) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{5}
}

func (x *RespuestaOferta) GetAceptado() bool {
	if x != nil {
		return x.Aceptado
	}
	return false
}

func (x *RespuestaOferta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaOferta) GetTermino() bool {
	if x != nil {
		return x.Termino
	}
	return false
}

// Mensaje que indica si una BD almacena correctamente una oferta
type RespuestaAlmacenarOferta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaAlmacenarOferta) Reset() {
	*x = RespuestaAlmacenarOferta{}
	mi := &file_proto_cyberday_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaAlmacenarOferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaAlmacenarOferta) ProtoMessage() {}

func (x *RespuestaAlmacenarOferta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaAlmacenarOferta.ProtoReflect.Descriptor instead.
func (*RespuestaAlmacenarOferta) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{6}
}

func (x *RespuestaAlmacenarOferta) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RespuestaAlmacenarOferta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Mensaje que solicita una resincronizacion incluyendo el id de la entidad
type SolicitudHistorialBD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdNodo        string                 `protobuf:"bytes,1,opt,name=id_nodo,json=idNodo,proto3" json:"id_nodo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudHistorialBD) Reset() {
	*x = SolicitudHistorialBD{}
	mi := &file_proto_cyberday_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudHistorialBD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudHistorialBD) ProtoMessage() {}

func (x *SolicitudHistorialBD) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudHistorialBD.ProtoReflect.Descriptor instead.
func (*SolicitudHistorialBD) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{7}
}

func (x *SolicitudHistorialBD) GetIdNodo() string {
	if x != nil {
		return x.IdNodo
	}
	return ""
}

// Mensaje que incluye el historial de ofertas
type RespuestaHistorialBD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ofertas       []*Oferta              `protobuf:"bytes,1,rep,name=Ofertas,proto3" json:"Ofertas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaHistorialBD) Reset() {
	*x = RespuestaHistorialBD{}
	mi := &file_proto_cyberday_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaHistorialBD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaHistorialBD) ProtoMessage() {}

func (x *RespuestaHistorialBD) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaHistorialBD.ProtoReflect.Descriptor instead.
func (*RespuestaHistorialBD) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{8}
}

func (x *RespuestaHistorialBD) GetOfertas() []*Oferta {
	if x != nil {
		return x.Ofertas
	}
	return nil
}

// Mensaje que indica si un consumidor recibio exitosamente una oferta
type RespuestaConsumidor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaConsumidor) Reset() {
	*x = RespuestaConsumidor{}
	mi := &file_proto_cyberday_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaConsumidor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaConsumidor) ProtoMessage() {}

func (x *RespuestaConsumidor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaConsumidor.ProtoReflect.Descriptor instead.
func (*RespuestaConsumidor) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{9}
}

func (x *RespuestaConsumidor) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RespuestaConsumidor) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Mensaje que notifica si es momento de terminar y forzar que no hayan mas caidas
type NotificarFin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fin           bool                   `protobuf:"varint,1,opt,name=fin,proto3" json:"fin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificarFin) Reset() {
	*x = NotificarFin{}
	mi := &file_proto_cyberday_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificarFin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificarFin) ProtoMessage() {}

func (x *NotificarFin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificarFin.ProtoReflect.Descriptor instead.
func (*NotificarFin) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{10}
}

func (x *NotificarFin) GetFin() bool {
	if x != nil {
		return x.Fin
	}
	return false
}

// Confirmaciones finalizacion por parte de BDs y Consumidores
type ConfirmacionFin struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Confirmacionbd         bool                   `protobuf:"varint,1,opt,name=confirmacionbd,proto3" json:"confirmacionbd,omitempty"`
	Confirmacionconsumidor bool                   `protobuf:"varint,2,opt,name=confirmacionconsumidor,proto3" json:"confirmacionconsumidor,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfirmacionFin) Reset() {
	*x = ConfirmacionFin{}
	mi := &file_proto_cyberday_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionFin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionFin) ProtoMessage() {}

func (x *ConfirmacionFin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionFin.ProtoReflect.Descriptor instead.
func (*ConfirmacionFin) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmacionFin) GetConfirmacionbd() bool {
	if x != nil {
		return x.Confirmacionbd
	}
	return false
}

func (x *ConfirmacionFin) GetConfirmacionconsumidor() bool {
	if x != nil {
		return x.Confirmacionconsumidor
	}
	return false
}

// Mensaje que envia el consumidor para solicitar el historico
type SolicitudHistorialConsumer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdConsumidor  string                 `protobuf:"bytes,1,opt,name=id_consumidor,json=idConsumidor,proto3" json:"id_consumidor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudHistorialConsumer) Reset() {
	*x = SolicitudHistorialConsumer{}
	mi := &file_proto_cyberday_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudHistorialConsumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudHistorialConsumer) ProtoMessage() {}

func (x *SolicitudHistorialConsumer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudHistorialConsumer.ProtoReflect.Descriptor instead.
func (*SolicitudHistorialConsumer) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{12}
}

func (x *SolicitudHistorialConsumer) GetIdConsumidor() string {
	if x != nil {
		return x.IdConsumidor
	}
	return ""
}

// Mensaje que incluye el historico filtrado
type RespuestaHistorialConsumer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ofertas       []*Oferta              `protobuf:"bytes,1,rep,name=Ofertas,proto3" json:"Ofertas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaHistorialConsumer) Reset() {
	*x = RespuestaHistorialConsumer{}
	mi := &file_proto_cyberday_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaHistorialConsumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaHistorialConsumer) ProtoMessage() {}

func (x *RespuestaHistorialConsumer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaHistorialConsumer.ProtoReflect.Descriptor instead.
func (*RespuestaHistorialConsumer) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{13}
}

func (x *RespuestaHistorialConsumer) GetOfertas() []*Oferta {
	if x != nil {
		return x.Ofertas
	}
	return nil
}

// Mensaje que incluye el id y tipo de entidad que reporta la caida
type FailNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailNotify) Reset() {
	*x = FailNotify{}
	mi := &file_proto_cyberday_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailNotify) ProtoMessage() {}

func (x *FailNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailNotify.ProtoReflect.Descriptor instead.
func (*FailNotify) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{14}
}

func (x *FailNotify) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FailNotify) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

// Mensaje de acknowledgment sobre la caida
type FailACK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailACK) Reset() {
	*x = FailACK{}
	mi := &file_proto_cyberday_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailACK) ProtoMessage() {}

func (x *FailACK) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailACK.ProtoReflect.Descriptor instead.
func (*FailACK) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{15}
}

func (x *FailACK) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_proto_cyberday_proto protoreflect.FileDescriptor

const file_proto_cyberday_proto_rawDesc = "" +
	"\n" +
	"\x14proto/cyberday.proto\x12\bcyberday\"s\n" +
	"\x11SolicitudRegistro\x12\x1d\n" +
	"\n" +
	"id_entidad\x18\x01 \x01(\tR\tidEntidad\x12!\n" +
	"\ftipo_entidad\x18\x02 \x01(\tR\vtipoEntidad\x12\x1c\n" +
	"\tdireccion\x18\x03 \x01(\tR\tdireccion\"C\n" +
	"\x11RespuestaRegistro\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\x11\n" +
	"\x0fSolicitudInicio\"'\n" +
	"\x0fRespuestaInicio\x12\x14\n" +
	"\x05listo\x18\x01 \x01(\bR\x05listo\"\xd9\x01\n" +
	"\x06Oferta\x12\x1b\n" +
	"\toferta_id\x18\x01 \x01(\tR\bofertaId\x12\x16\n" +
	"\x06tienda\x18\x02 \x01(\tR\x06tienda\x12\x1c\n" +
	"\tcategoria\x18\x03 \x01(\tR\tcategoria\x12\x1a\n" +
	"\bproducto\x18\x04 \x01(\tR\bproducto\x12\x16\n" +
	"\x06precio\x18\x05 \x01(\x03R\x06precio\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x14\n" +
	"\x05fecha\x18\a \x01(\tR\x05fecha\x12\x1c\n" +
	"\tdescuento\x18\b \x01(\x02R\tdescuento\"a\n" +
	"\x0fRespuestaOferta\x12\x1a\n" +
	"\baceptado\x18\x01 \x01(\bR\baceptado\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x18\n" +
	"\atermino\x18\x03 \x01(\bR\atermino\"J\n" +
	"\x18RespuestaAlmacenarOferta\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"/\n" +
	"\x14SolicitudHistorialBD\x12\x17\n" +
	"\aid_nodo\x18\x01 \x01(\tR\x06idNodo\"B\n" +
	"\x14RespuestaHistorialBD\x12*\n" +
	"\aOfertas\x18\x01 \x03(\v2\x10.cyberday.OfertaR\aOfertas\"E\n" +
	"\x13RespuestaConsumidor\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\" \n" +
	"\fNotificarFin\x12\x10\n" +
	"\x03fin\x18\x01 \x01(\bR\x03fin\"q\n" +
	"\x0fConfirmacionFin\x12&\n" +
	"\x0econfirmacionbd\x18\x01 \x01(\bR\x0econfirmacionbd\x126\n" +
	"\x16confirmacionconsumidor\x18\x02 \x01(\bR\x16confirmacionconsumidor\"A\n" +
	"\x1aSolicitudHistorialConsumer\x12#\n" +
	"\rid_consumidor\x18\x01 \x01(\tR\fidConsumidor\"H\n" +
	"\x1aRespuestaHistorialConsumer\x12*\n" +
	"\aOfertas\x18\x01 \x03(\v2\x10.cyberday.OfertaR\aOfertas\"0\n" +
	"\n" +
	"FailNotify\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\"\x1b\n" +
	"\aFailACK\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack2a\n" +
	"\x11RegistroEntidades\x12L\n" +
	"\x10RegistrarEntidad\x12\x1b.cyberday.SolicitudRegistro\x1a\x1b.cyberday.RespuestaRegistro2W\n" +
	"\x0fConfirmarInicio\x12D\n" +
	"\fConfirmacion\x12\x19.cyberday.SolicitudInicio\x1a\x19.cyberday.RespuestaInicio2F\n" +
	"\aOfertas\x12;\n" +
	"\fEnviarOferta\x12\x10.cyberday.Oferta\x1a\x19.cyberday.RespuestaOferta2\xa8\x01\n" +
	"\x06NodoDB\x12G\n" +
	"\x0fAlmacenarOferta\x12\x10.cyberday.Oferta\x1a\".cyberday.RespuestaAlmacenarOferta\x12U\n" +
	"\x13GetHistorialOfertas\x12\x1e.cyberday.SolicitudHistorialBD\x1a\x1e.cyberday.RespuestaHistorialBD2L\n" +
	"\bConsumer\x12@\n" +
	"\rRecibirOferta\x12\x10.cyberday.Oferta\x1a\x1d.cyberday.RespuestaConsumidor2Y\n" +
	"\fFinalizacion\x12I\n" +
	"\x14InformarFinalizacion\x12\x16.cyberday.NotificarFin\x1a\x19.cyberday.ConfirmacionFin2n\n" +
	"\bRecovery\x12b\n" +
	"\x14GetHistorialFiltrado\x12$.cyberday.SolicitudHistorialConsumer\x1a$.cyberday.RespuestaHistorialConsumer2A\n" +
	"\x05Caida\x128\n" +
	"\rInformarCaida\x12\x14.cyberday.FailNotify\x1a\x11.cyberday.FailACKB\rZ\v./;cyberdayb\x06proto3"

var (
	file_proto_cyberday_proto_rawDescOnce sync.Once
	file_proto_cyberday_proto_rawDescData []byte
)

func file_proto_cyberday_proto_rawDescGZIP() []byte {
	file_proto_cyberday_proto_rawDescOnce.Do(func() {
		file_proto_cyberday_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cyberday_proto_rawDesc), len(file_proto_cyberday_proto_rawDesc)))
	})
	return file_proto_cyberday_proto_rawDescData
}

var file_proto_cyberday_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_cyberday_proto_goTypes = []any{
	(*SolicitudRegistro)(nil),          // 0: cyberday.SolicitudRegistro
	(*RespuestaRegistro)(nil),          // 1: cyberday.RespuestaRegistro
	(*SolicitudInicio)(nil),            // 2: cyberday.SolicitudInicio
	(*RespuestaInicio)(nil),            // 3: cyberday.RespuestaInicio
	(*Oferta)(nil),                     // 4: cyberday.Oferta
	(*RespuestaOferta)(nil),            // 5: cyberday.RespuestaOferta
	(*RespuestaAlmacenarOferta)(nil),   // 6: cyberday.RespuestaAlmacenarOferta
	(*SolicitudHistorialBD)(nil),       // 7: cyberday.SolicitudHistorialBD
	(*RespuestaHistorialBD)(nil),       // 8: cyberday.RespuestaHistorialBD
	(*RespuestaConsumidor)(nil),        // 9: cyberday.RespuestaConsumidor
	(*NotificarFin)(nil),               // 10: cyberday.NotificarFin
	(*ConfirmacionFin)(nil),            // 11: cyberday.ConfirmacionFin
	(*SolicitudHistorialConsumer)(nil), // 12: cyberday.SolicitudHistorialConsumer
	(*RespuestaHistorialConsumer)(nil), // 13: cyberday.RespuestaHistorialConsumer
	(*FailNotify)(nil),                 // 14: cyberday.FailNotify
	(*FailACK)(nil),                    // 15: cyberday.FailACK
}
var file_proto_cyberday_proto_depIdxs = []int32{
	4,  // 0: cyberday.RespuestaHistorialBD.Ofertas:type_name -> cyberday.Oferta
	4,  // 1: cyberday.RespuestaHistorialConsumer.Ofertas:type_name -> cyberday.Oferta
	0,  // 2: cyberday.RegistroEntidades.RegistrarEntidad:input_type -> cyberday.SolicitudRegistro
	2,  // 3: cyberday.ConfirmarInicio.Confirmacion:input_type -> cyberday.SolicitudInicio
	4,  // 4: cyberday.Ofertas.EnviarOferta:input_type -> cyberday.Oferta
	4,  // 5: cyberday.NodoDB.AlmacenarOferta:input_type -> cyberday.Oferta
	7,  // 6: cyberday.NodoDB.GetHistorialOfertas:input_type -> cyberday.SolicitudHistorialBD
	4,  // 7: cyberday.Consumer.RecibirOferta:input_type -> cyberday.Oferta
	10, // 8: cyberday.Finalizacion.InformarFinalizacion:input_type -> cyberday.NotificarFin
	12, // 9: cyberday.Recovery.GetHistorialFiltrado:input_type -> cyberday.SolicitudHistorialConsumer
	14, // 10: cyberday.Caida.InformarCaida:input_type -> cyberday.FailNotify
	1,  // 11: cyberday.RegistroEntidades.RegistrarEntidad:output_type -> cyberday.RespuestaRegistro
	3,  // 12: cyberday.ConfirmarInicio.Confirmacion:output_type -> cyberday.RespuestaInicio
	5,  // 13: cyberday.Ofertas.EnviarOferta:output_type -> cyberday.RespuestaOferta
	6,  // 14: cyberday.NodoDB.AlmacenarOferta:output_type -> cyberday.RespuestaAlmacenarOferta
	8,  // 15: cyberday.NodoDB.GetHistorialOfertas:output_type -> cyberday.RespuestaHistorialBD
	9,  // 16: cyberday.Consumer.RecibirOferta:output_type -> cyberday.RespuestaConsumidor
	11, // 17: cyberday.Finalizacion.InformarFinalizacion:output_type -> cyberday.ConfirmacionFin
	13, // 18: cyberday.Recovery.GetHistorialFiltrado:output_type -> cyberday.RespuestaHistorialConsumer
	15, // 19: cyberday.Caida.InformarCaida:output_type -> cyberday.FailACK
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cyberday_proto_init() }
func file_proto_cyberday_proto_init() {
	if File_proto_cyberday_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cyberday_proto_rawDesc), len(file_proto_cyberday_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   8,
		},
		GoTypes:           file_proto_cyberday_proto_goTypes,
		DependencyIndexes: file_proto_cyberday_proto_depIdxs,
		MessageInfos:      file_proto_cyberday_proto_msgTypes,
	}.Build()
	File_proto_cyberday_proto = out.File
	file_proto_cyberday_proto_goTypes = nil
	file_proto_cyberday_proto_depIdxs = nil
}
