services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    ports:
      - "5673:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    

  lester:
    build:
      context: ./lester
    container_name: Lester
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq
    

  franklin:
    build:
      context: ./franklin
    container_name: Franklin
    ports:
      - "50052:50051"
    depends_on:
      - rabbitmq
    

  trevor:
    build:
      context: ./trevor 
    container_name: Trevor
    ports:
      - "50053:50051"
    depends_on:
      - rabbitmq
    


  michael:
    build:
      context: ./michael 
    container_name: Michael
    depends_on:
      - lester
      - franklin
      - trevor
    
    
