services:
  lester:
    build:
      context: ./lester
    container_name: Lester
    ports:
      - "50051:50051"

  franklin:
    build:
      context: ./franklin
    container_name: Franklin
    ports:
      - "50052:50051"

  trevor:
    build:
      context: ./trevor 
    container_name: Trevor
    ports:
      - "50053:50051"

  michael:
    build:
      context: ./michael 
    container_name: Michael
    depends_on:
      - lester
      - franklin
      - trevor