services:
  lester:
    build:
      context: .  
      dockerfile: lester/Dockerfile  
    container_name: Lester
    ports:
      - "50051:50051"
    networks:
      - Wasap

  franklin:
    build:
      context: .  
      dockerfile: franklin/Dockerfile  
    container_name: Franklin
    ports:
      - "50052:50051"
    networks:
      - Wasap

  trevor:
    build:
      context: .  
      dockerfile: trevor/Dockerfile  
    container_name: Trevor
    ports:
      - "50053:50051"
    networks:
      - Wasap

  michael:
    build:
      context: .  
      dockerfile: michael/Dockerfile  
    container_name: Michael
    depends_on:
      - lester
      - franklin
      - trevor
    networks:
      - Wasap
    stdin_open: true
    tty: true

networks:
  Wasap:
    driver: bridge