// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: trevor/proto/atraco.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Michael notifica a Trevor/Franklin para proceder con fase 2
type InfoDistraccion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProbabilidadExito float32                `protobuf:"fixed32,1,opt,name=probabilidad_exito,json=probabilidadExito,proto3" json:"probabilidad_exito,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InfoDistraccion) Reset() {
	*x = InfoDistraccion{}
	mi := &file_trevor_proto_atraco_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoDistraccion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoDistraccion) ProtoMessage() {}

func (x *InfoDistraccion) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_atraco_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoDistraccion.ProtoReflect.Descriptor instead.
func (*InfoDistraccion) Descriptor() ([]byte, []int) {
	return file_trevor_proto_atraco_proto_rawDescGZIP(), []int{0}
}

func (x *InfoDistraccion) GetProbabilidadExito() float32 {
	if x != nil {
		return x.ProbabilidadExito
	}
	return 0
}

// Trevor/Franklin responden a Michael con el resultado de la fase 2
type ResultadoDistraccion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Motivo        string                 `protobuf:"bytes,2,opt,name=motivo,proto3" json:"motivo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoDistraccion) Reset() {
	*x = ResultadoDistraccion{}
	mi := &file_trevor_proto_atraco_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoDistraccion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoDistraccion) ProtoMessage() {}

func (x *ResultadoDistraccion) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_atraco_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoDistraccion.ProtoReflect.Descriptor instead.
func (*ResultadoDistraccion) Descriptor() ([]byte, []int) {
	return file_trevor_proto_atraco_proto_rawDescGZIP(), []int{1}
}

func (x *ResultadoDistraccion) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ResultadoDistraccion) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

// Michael notifica a Trevor/Franklin para proceder con fase 3
type InfoGolpe struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProbabilidadExito float32                `protobuf:"fixed32,1,opt,name=probabilidad_exito,json=probabilidadExito,proto3" json:"probabilidad_exito,omitempty"`
	Botin             int32                  `protobuf:"varint,2,opt,name=botin,proto3" json:"botin,omitempty"`
	RiesgoPolicial    float32                `protobuf:"fixed32,3,opt,name=riesgo_policial,json=riesgoPolicial,proto3" json:"riesgo_policial,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InfoGolpe) Reset() {
	*x = InfoGolpe{}
	mi := &file_trevor_proto_atraco_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoGolpe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoGolpe) ProtoMessage() {}

func (x *InfoGolpe) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_atraco_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoGolpe.ProtoReflect.Descriptor instead.
func (*InfoGolpe) Descriptor() ([]byte, []int) {
	return file_trevor_proto_atraco_proto_rawDescGZIP(), []int{2}
}

func (x *InfoGolpe) GetProbabilidadExito() float32 {
	if x != nil {
		return x.ProbabilidadExito
	}
	return 0
}

func (x *InfoGolpe) GetBotin() int32 {
	if x != nil {
		return x.Botin
	}
	return 0
}

func (x *InfoGolpe) GetRiesgoPolicial() float32 {
	if x != nil {
		return x.RiesgoPolicial
	}
	return 0
}

// Trevor/Franklin responden a Michael con el resultado de la fase 3
type ResultadoGolpe struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Exito          bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Botin          int32                  `protobuf:"varint,2,opt,name=botin,proto3" json:"botin,omitempty"`
	Motivo         string                 `protobuf:"bytes,3,opt,name=motivo,proto3" json:"motivo,omitempty"`
	BotinExtra     int32                  `protobuf:"varint,4,opt,name=botin_extra,json=botinExtra,proto3" json:"botin_extra,omitempty"`
	EstrellasFinal int32                  `protobuf:"varint,5,opt,name=estrellas_final,json=estrellasFinal,proto3" json:"estrellas_final,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResultadoGolpe) Reset() {
	*x = ResultadoGolpe{}
	mi := &file_trevor_proto_atraco_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoGolpe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoGolpe) ProtoMessage() {}

func (x *ResultadoGolpe) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_atraco_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoGolpe.ProtoReflect.Descriptor instead.
func (*ResultadoGolpe) Descriptor() ([]byte, []int) {
	return file_trevor_proto_atraco_proto_rawDescGZIP(), []int{3}
}

func (x *ResultadoGolpe) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ResultadoGolpe) GetBotin() int32 {
	if x != nil {
		return x.Botin
	}
	return 0
}

func (x *ResultadoGolpe) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

func (x *ResultadoGolpe) GetBotinExtra() int32 {
	if x != nil {
		return x.BotinExtra
	}
	return 0
}

func (x *ResultadoGolpe) GetEstrellasFinal() int32 {
	if x != nil {
		return x.EstrellasFinal
	}
	return 0
}

// Michael informa el total de la operacion a Trevor y Franklin y les paga su correspondencia
type MontoPagoMiembro struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Correspondencia int32                  `protobuf:"varint,1,opt,name=correspondencia,proto3" json:"correspondencia,omitempty"`
	Total           int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MontoPagoMiembro) Reset() {
	*x = MontoPagoMiembro{}
	mi := &file_trevor_proto_atraco_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MontoPagoMiembro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MontoPagoMiembro) ProtoMessage() {}

func (x *MontoPagoMiembro) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_atraco_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MontoPagoMiembro.ProtoReflect.Descriptor instead.
func (*MontoPagoMiembro) Descriptor() ([]byte, []int) {
	return file_trevor_proto_atraco_proto_rawDescGZIP(), []int{4}
}

func (x *MontoPagoMiembro) GetCorrespondencia() int32 {
	if x != nil {
		return x.Correspondencia
	}
	return 0
}

func (x *MontoPagoMiembro) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Trevor y Franklin confirman el pago y le responden a Michael
type ConfirmarPagoMiembro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correcto      bool                   `protobuf:"varint,1,opt,name=correcto,proto3" json:"correcto,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmarPagoMiembro) Reset() {
	*x = ConfirmarPagoMiembro{}
	mi := &file_trevor_proto_atraco_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmarPagoMiembro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmarPagoMiembro) ProtoMessage() {}

func (x *ConfirmarPagoMiembro) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_atraco_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmarPagoMiembro.ProtoReflect.Descriptor instead.
func (*ConfirmarPagoMiembro) Descriptor() ([]byte, []int) {
	return file_trevor_proto_atraco_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmarPagoMiembro) GetCorrecto() bool {
	if x != nil {
		return x.Correcto
	}
	return false
}

func (x *ConfirmarPagoMiembro) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_trevor_proto_atraco_proto protoreflect.FileDescriptor

const file_trevor_proto_atraco_proto_rawDesc = "" +
	"\n" +
	"\x19trevor/proto/atraco.proto\"@\n" +
	"\x0fInfoDistraccion\x12-\n" +
	"\x12probabilidad_exito\x18\x01 \x01(\x02R\x11probabilidadExito\"D\n" +
	"\x14ResultadoDistraccion\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x16\n" +
	"\x06motivo\x18\x02 \x01(\tR\x06motivo\"y\n" +
	"\tInfoGolpe\x12-\n" +
	"\x12probabilidad_exito\x18\x01 \x01(\x02R\x11probabilidadExito\x12\x14\n" +
	"\x05botin\x18\x02 \x01(\x05R\x05botin\x12'\n" +
	"\x0friesgo_policial\x18\x03 \x01(\x02R\x0eriesgoPolicial\"\x9e\x01\n" +
	"\x0eResultadoGolpe\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x14\n" +
	"\x05botin\x18\x02 \x01(\x05R\x05botin\x12\x16\n" +
	"\x06motivo\x18\x03 \x01(\tR\x06motivo\x12\x1f\n" +
	"\vbotin_extra\x18\x04 \x01(\x05R\n" +
	"botinExtra\x12'\n" +
	"\x0festrellas_final\x18\x05 \x01(\x05R\x0eestrellasFinal\"R\n" +
	"\x10MontoPagoMiembro\x12(\n" +
	"\x0fcorrespondencia\x18\x01 \x01(\x05R\x0fcorrespondencia\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"L\n" +
	"\x14ConfirmarPagoMiembro\x12\x1a\n" +
	"\bcorrecto\x18\x01 \x01(\bR\bcorrecto\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje2\xbf\x01\n" +
	"\x15MichaelTrevorFranklin\x12>\n" +
	"\x13InformarDistraccion\x12\x10.InfoDistraccion\x1a\x15.ResultadoDistraccion\x12,\n" +
	"\rInformarGolpe\x12\n" +
	".InfoGolpe\x1a\x0f.ResultadoGolpe\x128\n" +
	"\fPagarMiembro\x12\x11.MontoPagoMiembro\x1a\x15.ConfirmarPagoMiembroB\x0eZ\ftrevor/protob\x06proto3"

var (
	file_trevor_proto_atraco_proto_rawDescOnce sync.Once
	file_trevor_proto_atraco_proto_rawDescData []byte
)

func file_trevor_proto_atraco_proto_rawDescGZIP() []byte {
	file_trevor_proto_atraco_proto_rawDescOnce.Do(func() {
		file_trevor_proto_atraco_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trevor_proto_atraco_proto_rawDesc), len(file_trevor_proto_atraco_proto_rawDesc)))
	})
	return file_trevor_proto_atraco_proto_rawDescData
}

var file_trevor_proto_atraco_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_trevor_proto_atraco_proto_goTypes = []any{
	(*InfoDistraccion)(nil),      // 0: InfoDistraccion
	(*ResultadoDistraccion)(nil), // 1: ResultadoDistraccion
	(*InfoGolpe)(nil),            // 2: InfoGolpe
	(*ResultadoGolpe)(nil),       // 3: ResultadoGolpe
	(*MontoPagoMiembro)(nil),     // 4: MontoPagoMiembro
	(*ConfirmarPagoMiembro)(nil), // 5: ConfirmarPagoMiembro
}
var file_trevor_proto_atraco_proto_depIdxs = []int32{
	0, // 0: MichaelTrevorFranklin.InformarDistraccion:input_type -> InfoDistraccion
	2, // 1: MichaelTrevorFranklin.InformarGolpe:input_type -> InfoGolpe
	4, // 2: MichaelTrevorFranklin.PagarMiembro:input_type -> MontoPagoMiembro
	1, // 3: MichaelTrevorFranklin.InformarDistraccion:output_type -> ResultadoDistraccion
	3, // 4: MichaelTrevorFranklin.InformarGolpe:output_type -> ResultadoGolpe
	5, // 5: MichaelTrevorFranklin.PagarMiembro:output_type -> ConfirmarPagoMiembro
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trevor_proto_atraco_proto_init() }
func file_trevor_proto_atraco_proto_init() {
	if File_trevor_proto_atraco_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trevor_proto_atraco_proto_rawDesc), len(file_trevor_proto_atraco_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trevor_proto_atraco_proto_goTypes,
		DependencyIndexes: file_trevor_proto_atraco_proto_depIdxs,
		MessageInfos:      file_trevor_proto_atraco_proto_msgTypes,
	}.Build()
	File_trevor_proto_atraco_proto = out.File
	file_trevor_proto_atraco_proto_goTypes = nil
	file_trevor_proto_atraco_proto_depIdxs = nil
}
