// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/aerodist.proto

package aerodist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Solicitud de Check-in / Escritura
type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,3,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	RequestUuid   string                 `protobuf:"bytes,4,opt,name=request_uuid,json=requestUuid,proto3" json:"request_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_proto_aerodist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{0}
}

func (x *CheckInRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckInRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *CheckInRequest) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *CheckInRequest) GetRequestUuid() string {
	if x != nil {
		return x.RequestUuid
	}
	return ""
}

// Respuesta de Check-in (se quitó 'optional')
type CheckInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorDetails  string                 `protobuf:"bytes,3,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_proto_aerodist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckInResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckInResponse) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

// Solicitud de Tarjeta de Embarque / Lectura (inmediata post-escritura)
type BoardingPassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardingPassRequest) Reset() {
	*x = BoardingPassRequest{}
	mi := &file_proto_aerodist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardingPassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardingPassRequest) ProtoMessage() {}

func (x *BoardingPassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardingPassRequest.ProtoReflect.Descriptor instead.
func (*BoardingPassRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{2}
}

func (x *BoardingPassRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BoardingPassRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

// Respuesta con la Tarjeta de Embarque / Lectura
type BoardingPassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	SeatAssigned  string                 `protobuf:"bytes,3,opt,name=seat_assigned,json=seatAssigned,proto3" json:"seat_assigned,omitempty"`
	Gate          string                 `protobuf:"bytes,4,opt,name=gate,proto3" json:"gate,omitempty"` // ... más detalles del boarding pass
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardingPassResponse) Reset() {
	*x = BoardingPassResponse{}
	mi := &file_proto_aerodist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardingPassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardingPassResponse) ProtoMessage() {}

func (x *BoardingPassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardingPassResponse.ProtoReflect.Descriptor instead.
func (*BoardingPassResponse) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{3}
}

func (x *BoardingPassResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BoardingPassResponse) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *BoardingPassResponse) GetSeatAssigned() string {
	if x != nil {
		return x.SeatAssigned
	}
	return ""
}

func (x *BoardingPassResponse) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

// Solicitud de actualización interna de datos de asiento (escritura RYW)
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,3,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	RequestUuid   string                 `protobuf:"bytes,4,opt,name=request_uuid,json=requestUuid,proto3" json:"request_uuid,omitempty"` // Puede incluir el vector clock si se usa para la escritura
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_aerodist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *UpdateRequest) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *UpdateRequest) GetRequestUuid() string {
	if x != nil {
		return x.RequestUuid
	}
	return ""
}

// NUEVO: Solicitud de actualización de estado de vuelo (Consistencia Eventual / Gossip)
type UpdateFlightStatusRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FlightId string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	// Mapa para Status: Ej. {"update_type": "update_value"}
	Status map[string]string `protobuf:"bytes,2,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Reloj Vectorial: Ej. {"DN-1": 5, "DN-2": 2}
	VectorClock   map[string]int64 `protobuf:"bytes,3,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFlightStatusRequest) Reset() {
	*x = UpdateFlightStatusRequest{}
	mi := &file_proto_aerodist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFlightStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlightStatusRequest) ProtoMessage() {}

func (x *UpdateFlightStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlightStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlightStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFlightStatusRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *UpdateFlightStatusRequest) GetStatus() map[string]string {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UpdateFlightStatusRequest) GetVectorClock() map[string]int64 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type UpdateResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Success    bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DatanodeId string                 `protobuf:"bytes,3,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	// ✅ Campo para RYW: El Vector Clock final de la escritura (de DN)
	VectorClock   map[string]int64 `protobuf:"bytes,4,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_aerodist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateResponse) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

func (x *UpdateResponse) GetVectorClock() map[string]int64 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// Solicitud de lectura de datos de vuelo (RYW/Monotonic)
type ReadRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlightId string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	// ✅ Campo para RYW: El Vector Clock que el cliente vio por última vez
	ClientVectorClock map[string]int64 `protobuf:"bytes,3,rep,name=client_vector_clock,json=clientVectorClock,proto3" json:"client_vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_aerodist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{7}
}

func (x *ReadRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReadRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *ReadRequest) GetClientVectorClock() map[string]int64 {
	if x != nil {
		return x.ClientVectorClock
	}
	return nil
}

type ReadResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FlightId             string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	SeatAssignedToClient string                 `protobuf:"bytes,2,opt,name=seat_assigned_to_client,json=seatAssignedToClient,proto3" json:"seat_assigned_to_client,omitempty"`
	// ✅ Campo para RYW: El Vector Clock devuelto por el Datanode
	VectorClock   map[string]int64 `protobuf:"bytes,3,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // ... más campos
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_aerodist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{8}
}

func (x *ReadResponse) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *ReadResponse) GetSeatAssignedToClient() string {
	if x != nil {
		return x.SeatAssignedToClient
	}
	return ""
}

func (x *ReadResponse) GetVectorClock() map[string]int64 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// Para las consultas de vuelo (usado por el cliente Observador)
type FlightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightID      string                 `protobuf:"bytes,1,opt,name=flightID,proto3" json:"flightID,omitempty"`        // ID del vuelo para consultar
	Lastversion   int64                  `protobuf:"varint,2,opt,name=lastversion,proto3" json:"lastversion,omitempty"` // Versión escalar del último dato conocido (para Monotonic Reads)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightRequest) Reset() {
	*x = FlightRequest{}
	mi := &file_proto_aerodist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightRequest) ProtoMessage() {}

func (x *FlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightRequest.ProtoReflect.Descriptor instead.
func (*FlightRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{9}
}

func (x *FlightRequest) GetFlightID() string {
	if x != nil {
		return x.FlightID
	}
	return ""
}

func (x *FlightRequest) GetLastversion() int64 {
	if x != nil {
		return x.Lastversion
	}
	return 0
}

// Respuesta para la consulta del estado de un vuelo (usado por el cliente Observador)
type FlightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightID      string                 `protobuf:"bytes,1,opt,name=flightID,proto3" json:"flightID,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`    // Ejemplo: "OnTime", "Delayed"
	Gate          string                 `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`        // Ejemplo: "G4"
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // Versión escalar del dato que se devuelve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightResponse) Reset() {
	*x = FlightResponse{}
	mi := &file_proto_aerodist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightResponse) ProtoMessage() {}

func (x *FlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightResponse.ProtoReflect.Descriptor instead.
func (*FlightResponse) Descriptor() ([]byte, []int) {
	return file_proto_aerodist_proto_rawDescGZIP(), []int{10}
}

func (x *FlightResponse) GetFlightID() string {
	if x != nil {
		return x.FlightID
	}
	return ""
}

func (x *FlightResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FlightResponse) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *FlightResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_proto_aerodist_proto protoreflect.FileDescriptor

const file_proto_aerodist_proto_rawDesc = "" +
	"\n" +
	"\x14proto/aerodist.proto\x12\baerodist\"\x8e\x01\n" +
	"\x0eCheckInRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\x12\x1f\n" +
	"\vseat_number\x18\x03 \x01(\tR\n" +
	"seatNumber\x12!\n" +
	"\frequest_uuid\x18\x04 \x01(\tR\vrequestUuid\"j\n" +
	"\x0fCheckInResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rerror_details\x18\x03 \x01(\tR\ferrorDetails\"O\n" +
	"\x13BoardingPassRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\"\x89\x01\n" +
	"\x14BoardingPassResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\x12#\n" +
	"\rseat_assigned\x18\x03 \x01(\tR\fseatAssigned\x12\x12\n" +
	"\x04gate\x18\x04 \x01(\tR\x04gate\"\x8d\x01\n" +
	"\rUpdateRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\x12\x1f\n" +
	"\vseat_number\x18\x03 \x01(\tR\n" +
	"seatNumber\x12!\n" +
	"\frequest_uuid\x18\x04 \x01(\tR\vrequestUuid\"\xd5\x02\n" +
	"\x19UpdateFlightStatusRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12G\n" +
	"\x06status\x18\x02 \x03(\v2/.aerodist.UpdateFlightStatusRequest.StatusEntryR\x06status\x12W\n" +
	"\fvector_clock\x18\x03 \x03(\v24.aerodist.UpdateFlightStatusRequest.VectorClockEntryR\vvectorClock\x1a9\n" +
	"\vStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xf3\x01\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vdatanode_id\x18\x03 \x01(\tR\n" +
	"datanodeId\x12L\n" +
	"\fvector_clock\x18\x04 \x03(\v2).aerodist.UpdateResponse.VectorClockEntryR\vvectorClock\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xeb\x01\n" +
	"\vReadRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\x12\\\n" +
	"\x13client_vector_clock\x18\x03 \x03(\v2,.aerodist.ReadRequest.ClientVectorClockEntryR\x11clientVectorClock\x1aD\n" +
	"\x16ClientVectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xee\x01\n" +
	"\fReadResponse\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x125\n" +
	"\x17seat_assigned_to_client\x18\x02 \x01(\tR\x14seatAssignedToClient\x12J\n" +
	"\fvector_clock\x18\x03 \x03(\v2'.aerodist.ReadResponse.VectorClockEntryR\vvectorClock\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"M\n" +
	"\rFlightRequest\x12\x1a\n" +
	"\bflightID\x18\x01 \x01(\tR\bflightID\x12 \n" +
	"\vlastversion\x18\x02 \x01(\x03R\vlastversion\"r\n" +
	"\x0eFlightResponse\x12\x1a\n" +
	"\bflightID\x18\x01 \x01(\tR\bflightID\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion2N\n" +
	"\x06Broker\x12D\n" +
	"\x0fGetFlightStatus\x12\x17.aerodist.FlightRequest\x1a\x18.aerodist.FlightResponse2\xa8\x02\n" +
	"\x0fDatanodeService\x12?\n" +
	"\n" +
	"ApplyWrite\x12\x17.aerodist.UpdateRequest\x1a\x18.aerodist.UpdateResponse\x129\n" +
	"\bReadData\x12\x15.aerodist.ReadRequest\x1a\x16.aerodist.ReadResponse\x12S\n" +
	"\x12UpdateFlightStatus\x12#.aerodist.UpdateFlightStatusRequest\x1a\x18.aerodist.UpdateResponse\x12D\n" +
	"\x0fGetFlightStatus\x12\x17.aerodist.FlightRequest\x1a\x18.aerodist.FlightResponse2\xad\x01\n" +
	"\x12CheckInCoordinator\x12E\n" +
	"\x0eProcessCheckIn\x12\x18.aerodist.CheckInRequest\x1a\x19.aerodist.CheckInResponse\x12P\n" +
	"\x0fGetBoardingPass\x12\x1d.aerodist.BoardingPassRequest\x1a\x1e.aerodist.BoardingPassResponse2\xb4\x02\n" +
	"\rCentralBroker\x12E\n" +
	"\x10UpdateFlightData\x12\x17.aerodist.UpdateRequest\x1a\x18.aerodist.UpdateResponse\x12>\n" +
	"\rGetFlightData\x12\x15.aerodist.ReadRequest\x1a\x16.aerodist.ReadResponse\x12V\n" +
	"\x15BroadcastFlightStatus\x12#.aerodist.UpdateFlightStatusRequest\x1a\x18.aerodist.UpdateResponse\x12D\n" +
	"\x0fGetFlightStatus\x12\x17.aerodist.FlightRequest\x1a\x18.aerodist.FlightResponseB\x12Z\x10./proto;aerodistb\x06proto3"

var (
	file_proto_aerodist_proto_rawDescOnce sync.Once
	file_proto_aerodist_proto_rawDescData []byte
)

func file_proto_aerodist_proto_rawDescGZIP() []byte {
	file_proto_aerodist_proto_rawDescOnce.Do(func() {
		file_proto_aerodist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aerodist_proto_rawDesc), len(file_proto_aerodist_proto_rawDesc)))
	})
	return file_proto_aerodist_proto_rawDescData
}

var file_proto_aerodist_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_aerodist_proto_goTypes = []any{
	(*CheckInRequest)(nil),            // 0: aerodist.CheckInRequest
	(*CheckInResponse)(nil),           // 1: aerodist.CheckInResponse
	(*BoardingPassRequest)(nil),       // 2: aerodist.BoardingPassRequest
	(*BoardingPassResponse)(nil),      // 3: aerodist.BoardingPassResponse
	(*UpdateRequest)(nil),             // 4: aerodist.UpdateRequest
	(*UpdateFlightStatusRequest)(nil), // 5: aerodist.UpdateFlightStatusRequest
	(*UpdateResponse)(nil),            // 6: aerodist.UpdateResponse
	(*ReadRequest)(nil),               // 7: aerodist.ReadRequest
	(*ReadResponse)(nil),              // 8: aerodist.ReadResponse
	(*FlightRequest)(nil),             // 9: aerodist.FlightRequest
	(*FlightResponse)(nil),            // 10: aerodist.FlightResponse
	nil,                               // 11: aerodist.UpdateFlightStatusRequest.StatusEntry
	nil,                               // 12: aerodist.UpdateFlightStatusRequest.VectorClockEntry
	nil,                               // 13: aerodist.UpdateResponse.VectorClockEntry
	nil,                               // 14: aerodist.ReadRequest.ClientVectorClockEntry
	nil,                               // 15: aerodist.ReadResponse.VectorClockEntry
}
var file_proto_aerodist_proto_depIdxs = []int32{
	11, // 0: aerodist.UpdateFlightStatusRequest.status:type_name -> aerodist.UpdateFlightStatusRequest.StatusEntry
	12, // 1: aerodist.UpdateFlightStatusRequest.vector_clock:type_name -> aerodist.UpdateFlightStatusRequest.VectorClockEntry
	13, // 2: aerodist.UpdateResponse.vector_clock:type_name -> aerodist.UpdateResponse.VectorClockEntry
	14, // 3: aerodist.ReadRequest.client_vector_clock:type_name -> aerodist.ReadRequest.ClientVectorClockEntry
	15, // 4: aerodist.ReadResponse.vector_clock:type_name -> aerodist.ReadResponse.VectorClockEntry
	9,  // 5: aerodist.Broker.GetFlightStatus:input_type -> aerodist.FlightRequest
	4,  // 6: aerodist.DatanodeService.ApplyWrite:input_type -> aerodist.UpdateRequest
	7,  // 7: aerodist.DatanodeService.ReadData:input_type -> aerodist.ReadRequest
	5,  // 8: aerodist.DatanodeService.UpdateFlightStatus:input_type -> aerodist.UpdateFlightStatusRequest
	9,  // 9: aerodist.DatanodeService.GetFlightStatus:input_type -> aerodist.FlightRequest
	0,  // 10: aerodist.CheckInCoordinator.ProcessCheckIn:input_type -> aerodist.CheckInRequest
	2,  // 11: aerodist.CheckInCoordinator.GetBoardingPass:input_type -> aerodist.BoardingPassRequest
	4,  // 12: aerodist.CentralBroker.UpdateFlightData:input_type -> aerodist.UpdateRequest
	7,  // 13: aerodist.CentralBroker.GetFlightData:input_type -> aerodist.ReadRequest
	5,  // 14: aerodist.CentralBroker.BroadcastFlightStatus:input_type -> aerodist.UpdateFlightStatusRequest
	9,  // 15: aerodist.CentralBroker.GetFlightStatus:input_type -> aerodist.FlightRequest
	10, // 16: aerodist.Broker.GetFlightStatus:output_type -> aerodist.FlightResponse
	6,  // 17: aerodist.DatanodeService.ApplyWrite:output_type -> aerodist.UpdateResponse
	8,  // 18: aerodist.DatanodeService.ReadData:output_type -> aerodist.ReadResponse
	6,  // 19: aerodist.DatanodeService.UpdateFlightStatus:output_type -> aerodist.UpdateResponse
	10, // 20: aerodist.DatanodeService.GetFlightStatus:output_type -> aerodist.FlightResponse
	1,  // 21: aerodist.CheckInCoordinator.ProcessCheckIn:output_type -> aerodist.CheckInResponse
	3,  // 22: aerodist.CheckInCoordinator.GetBoardingPass:output_type -> aerodist.BoardingPassResponse
	6,  // 23: aerodist.CentralBroker.UpdateFlightData:output_type -> aerodist.UpdateResponse
	8,  // 24: aerodist.CentralBroker.GetFlightData:output_type -> aerodist.ReadResponse
	6,  // 25: aerodist.CentralBroker.BroadcastFlightStatus:output_type -> aerodist.UpdateResponse
	10, // 26: aerodist.CentralBroker.GetFlightStatus:output_type -> aerodist.FlightResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_aerodist_proto_init() }
func file_proto_aerodist_proto_init() {
	if File_proto_aerodist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aerodist_proto_rawDesc), len(file_proto_aerodist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_aerodist_proto_goTypes,
		DependencyIndexes: file_proto_aerodist_proto_depIdxs,
		MessageInfos:      file_proto_aerodist_proto_msgTypes,
	}.Build()
	File_proto_aerodist_proto = out.File
	file_proto_aerodist_proto_goTypes = nil
	file_proto_aerodist_proto_depIdxs = nil
}
