// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/aerodist.proto

package aerodist

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Broker_GetFlightStatus_FullMethodName = "/aerodist.Broker/GetFlightStatus"
)

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio: Expuesto por el Broker Central para Pasajeros Observadores
type BrokerClient interface {
	// Consulta el estado de un vuelo, implementando la lógica de Monotonic Reads
	// El cliente llama a esta RPC: client.GetFlightStatus(req)
	GetFlightStatus(ctx context.Context, in *FlightRequest, opts ...grpc.CallOption) (*FlightResponse, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) GetFlightStatus(ctx context.Context, in *FlightRequest, opts ...grpc.CallOption) (*FlightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightResponse)
	err := c.cc.Invoke(ctx, Broker_GetFlightStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility.
//
// Servicio: Expuesto por el Broker Central para Pasajeros Observadores
type BrokerServer interface {
	// Consulta el estado de un vuelo, implementando la lógica de Monotonic Reads
	// El cliente llama a esta RPC: client.GetFlightStatus(req)
	GetFlightStatus(context.Context, *FlightRequest) (*FlightResponse, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServer struct{}

func (UnimplementedBrokerServer) GetFlightStatus(context.Context, *FlightRequest) (*FlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightStatus not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}
func (UnimplementedBrokerServer) testEmbeddedByValue()                {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	// If the following call pancis, it indicates UnimplementedBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_GetFlightStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetFlightStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GetFlightStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetFlightStatus(ctx, req.(*FlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aerodist.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlightStatus",
			Handler:    _Broker_GetFlightStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aerodist.proto",
}

const (
	DatanodeService_ApplyWrite_FullMethodName         = "/aerodist.DatanodeService/ApplyWrite"
	DatanodeService_ReadData_FullMethodName           = "/aerodist.DatanodeService/ReadData"
	DatanodeService_UpdateFlightStatus_FullMethodName = "/aerodist.DatanodeService/UpdateFlightStatus"
	DatanodeService_GetFlightStatus_FullMethodName    = "/aerodist.DatanodeService/GetFlightStatus"
)

// DatanodeServiceClient is the client API for DatanodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio expuesto por los Datanodes
type DatanodeServiceClient interface {
	// RYW: Recibe la solicitud de escritura del Broker
	ApplyWrite(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// RYW: Recibe la solicitud de lectura del Broker o el Coordinador
	ReadData(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// NUEVO (Eventual): RPC para recibir actualizaciones de estado de vuelo (Gossip/Broker)
	UpdateFlightStatus(ctx context.Context, in *UpdateFlightStatusRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	GetFlightStatus(ctx context.Context, in *FlightRequest, opts ...grpc.CallOption) (*FlightResponse, error)
}

type datanodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatanodeServiceClient(cc grpc.ClientConnInterface) DatanodeServiceClient {
	return &datanodeServiceClient{cc}
}

func (c *datanodeServiceClient) ApplyWrite(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, DatanodeService_ApplyWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) ReadData(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, DatanodeService_ReadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) UpdateFlightStatus(ctx context.Context, in *UpdateFlightStatusRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, DatanodeService_UpdateFlightStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) GetFlightStatus(ctx context.Context, in *FlightRequest, opts ...grpc.CallOption) (*FlightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightResponse)
	err := c.cc.Invoke(ctx, DatanodeService_GetFlightStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatanodeServiceServer is the server API for DatanodeService service.
// All implementations must embed UnimplementedDatanodeServiceServer
// for forward compatibility.
//
// Servicio expuesto por los Datanodes
type DatanodeServiceServer interface {
	// RYW: Recibe la solicitud de escritura del Broker
	ApplyWrite(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// RYW: Recibe la solicitud de lectura del Broker o el Coordinador
	ReadData(context.Context, *ReadRequest) (*ReadResponse, error)
	// NUEVO (Eventual): RPC para recibir actualizaciones de estado de vuelo (Gossip/Broker)
	UpdateFlightStatus(context.Context, *UpdateFlightStatusRequest) (*UpdateResponse, error)
	GetFlightStatus(context.Context, *FlightRequest) (*FlightResponse, error)
	mustEmbedUnimplementedDatanodeServiceServer()
}

// UnimplementedDatanodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatanodeServiceServer struct{}

func (UnimplementedDatanodeServiceServer) ApplyWrite(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyWrite not implemented")
}
func (UnimplementedDatanodeServiceServer) ReadData(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadData not implemented")
}
func (UnimplementedDatanodeServiceServer) UpdateFlightStatus(context.Context, *UpdateFlightStatusRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlightStatus not implemented")
}
func (UnimplementedDatanodeServiceServer) GetFlightStatus(context.Context, *FlightRequest) (*FlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightStatus not implemented")
}
func (UnimplementedDatanodeServiceServer) mustEmbedUnimplementedDatanodeServiceServer() {}
func (UnimplementedDatanodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatanodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatanodeServiceServer will
// result in compilation errors.
type UnsafeDatanodeServiceServer interface {
	mustEmbedUnimplementedDatanodeServiceServer()
}

func RegisterDatanodeServiceServer(s grpc.ServiceRegistrar, srv DatanodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDatanodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatanodeService_ServiceDesc, srv)
}

func _DatanodeService_ApplyWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).ApplyWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_ApplyWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).ApplyWrite(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_ReadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).ReadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_ReadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).ReadData(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_UpdateFlightStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlightStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).UpdateFlightStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_UpdateFlightStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).UpdateFlightStatus(ctx, req.(*UpdateFlightStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_GetFlightStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).GetFlightStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_GetFlightStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).GetFlightStatus(ctx, req.(*FlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatanodeService_ServiceDesc is the grpc.ServiceDesc for DatanodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatanodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aerodist.DatanodeService",
	HandlerType: (*DatanodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyWrite",
			Handler:    _DatanodeService_ApplyWrite_Handler,
		},
		{
			MethodName: "ReadData",
			Handler:    _DatanodeService_ReadData_Handler,
		},
		{
			MethodName: "UpdateFlightStatus",
			Handler:    _DatanodeService_UpdateFlightStatus_Handler,
		},
		{
			MethodName: "GetFlightStatus",
			Handler:    _DatanodeService_GetFlightStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aerodist.proto",
}

const (
	CheckInCoordinator_ProcessCheckIn_FullMethodName  = "/aerodist.CheckInCoordinator/ProcessCheckIn"
	CheckInCoordinator_GetBoardingPass_FullMethodName = "/aerodist.CheckInCoordinator/GetBoardingPass"
)

// CheckInCoordinatorClient is the client API for CheckInCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio expuesto por el Coordinador (Gateway de Check-in)
type CheckInCoordinatorClient interface {
	// 1. Escritura: Para Check-in y selección de asiento (RYW).
	ProcessCheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
	// 2. Lectura: Para obtener la Tarjeta de Embarque, forzando RYW.
	GetBoardingPass(ctx context.Context, in *BoardingPassRequest, opts ...grpc.CallOption) (*BoardingPassResponse, error)
}

type checkInCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckInCoordinatorClient(cc grpc.ClientConnInterface) CheckInCoordinatorClient {
	return &checkInCoordinatorClient{cc}
}

func (c *checkInCoordinatorClient) ProcessCheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, CheckInCoordinator_ProcessCheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkInCoordinatorClient) GetBoardingPass(ctx context.Context, in *BoardingPassRequest, opts ...grpc.CallOption) (*BoardingPassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardingPassResponse)
	err := c.cc.Invoke(ctx, CheckInCoordinator_GetBoardingPass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckInCoordinatorServer is the server API for CheckInCoordinator service.
// All implementations must embed UnimplementedCheckInCoordinatorServer
// for forward compatibility.
//
// Servicio expuesto por el Coordinador (Gateway de Check-in)
type CheckInCoordinatorServer interface {
	// 1. Escritura: Para Check-in y selección de asiento (RYW).
	ProcessCheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	// 2. Lectura: Para obtener la Tarjeta de Embarque, forzando RYW.
	GetBoardingPass(context.Context, *BoardingPassRequest) (*BoardingPassResponse, error)
	mustEmbedUnimplementedCheckInCoordinatorServer()
}

// UnimplementedCheckInCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckInCoordinatorServer struct{}

func (UnimplementedCheckInCoordinatorServer) ProcessCheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessCheckIn not implemented")
}
func (UnimplementedCheckInCoordinatorServer) GetBoardingPass(context.Context, *BoardingPassRequest) (*BoardingPassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoardingPass not implemented")
}
func (UnimplementedCheckInCoordinatorServer) mustEmbedUnimplementedCheckInCoordinatorServer() {}
func (UnimplementedCheckInCoordinatorServer) testEmbeddedByValue()                            {}

// UnsafeCheckInCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckInCoordinatorServer will
// result in compilation errors.
type UnsafeCheckInCoordinatorServer interface {
	mustEmbedUnimplementedCheckInCoordinatorServer()
}

func RegisterCheckInCoordinatorServer(s grpc.ServiceRegistrar, srv CheckInCoordinatorServer) {
	// If the following call pancis, it indicates UnimplementedCheckInCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckInCoordinator_ServiceDesc, srv)
}

func _CheckInCoordinator_ProcessCheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInCoordinatorServer).ProcessCheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckInCoordinator_ProcessCheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInCoordinatorServer).ProcessCheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckInCoordinator_GetBoardingPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardingPassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInCoordinatorServer).GetBoardingPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckInCoordinator_GetBoardingPass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInCoordinatorServer).GetBoardingPass(ctx, req.(*BoardingPassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckInCoordinator_ServiceDesc is the grpc.ServiceDesc for CheckInCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckInCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aerodist.CheckInCoordinator",
	HandlerType: (*CheckInCoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessCheckIn",
			Handler:    _CheckInCoordinator_ProcessCheckIn_Handler,
		},
		{
			MethodName: "GetBoardingPass",
			Handler:    _CheckInCoordinator_GetBoardingPass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aerodist.proto",
}

const (
	CentralBroker_UpdateFlightData_FullMethodName      = "/aerodist.CentralBroker/UpdateFlightData"
	CentralBroker_GetFlightData_FullMethodName         = "/aerodist.CentralBroker/GetFlightData"
	CentralBroker_BroadcastFlightStatus_FullMethodName = "/aerodist.CentralBroker/BroadcastFlightStatus"
	CentralBroker_GetFlightStatus_FullMethodName       = "/aerodist.CentralBroker/GetFlightStatus"
)

// CentralBrokerClient is the client API for CentralBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio expuesto por el Broker Central para interactuar con los Datanodes
type CentralBrokerClient interface {
	// RYW: El coordinador reenvía la solicitud de escritura al Broker
	UpdateFlightData(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// RYW/Monotonic: El coordinador pide al Broker que balancee una lectura
	GetFlightData(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// NUEVO (Eventual): El Broker inicia la distribución de la actualización del CSV a los Datanodes.
	BroadcastFlightStatus(ctx context.Context, in *UpdateFlightStatusRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// NUEVO: RPC dedicado para el Cliente Monotonic Reads (Pasajero Observador)
	GetFlightStatus(ctx context.Context, in *FlightRequest, opts ...grpc.CallOption) (*FlightResponse, error)
}

type centralBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewCentralBrokerClient(cc grpc.ClientConnInterface) CentralBrokerClient {
	return &centralBrokerClient{cc}
}

func (c *centralBrokerClient) UpdateFlightData(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, CentralBroker_UpdateFlightData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralBrokerClient) GetFlightData(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, CentralBroker_GetFlightData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralBrokerClient) BroadcastFlightStatus(ctx context.Context, in *UpdateFlightStatusRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, CentralBroker_BroadcastFlightStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralBrokerClient) GetFlightStatus(ctx context.Context, in *FlightRequest, opts ...grpc.CallOption) (*FlightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightResponse)
	err := c.cc.Invoke(ctx, CentralBroker_GetFlightStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CentralBrokerServer is the server API for CentralBroker service.
// All implementations must embed UnimplementedCentralBrokerServer
// for forward compatibility.
//
// Servicio expuesto por el Broker Central para interactuar con los Datanodes
type CentralBrokerServer interface {
	// RYW: El coordinador reenvía la solicitud de escritura al Broker
	UpdateFlightData(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// RYW/Monotonic: El coordinador pide al Broker que balancee una lectura
	GetFlightData(context.Context, *ReadRequest) (*ReadResponse, error)
	// NUEVO (Eventual): El Broker inicia la distribución de la actualización del CSV a los Datanodes.
	BroadcastFlightStatus(context.Context, *UpdateFlightStatusRequest) (*UpdateResponse, error)
	// NUEVO: RPC dedicado para el Cliente Monotonic Reads (Pasajero Observador)
	GetFlightStatus(context.Context, *FlightRequest) (*FlightResponse, error)
	mustEmbedUnimplementedCentralBrokerServer()
}

// UnimplementedCentralBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCentralBrokerServer struct{}

func (UnimplementedCentralBrokerServer) UpdateFlightData(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlightData not implemented")
}
func (UnimplementedCentralBrokerServer) GetFlightData(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightData not implemented")
}
func (UnimplementedCentralBrokerServer) BroadcastFlightStatus(context.Context, *UpdateFlightStatusRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastFlightStatus not implemented")
}
func (UnimplementedCentralBrokerServer) GetFlightStatus(context.Context, *FlightRequest) (*FlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightStatus not implemented")
}
func (UnimplementedCentralBrokerServer) mustEmbedUnimplementedCentralBrokerServer() {}
func (UnimplementedCentralBrokerServer) testEmbeddedByValue()                       {}

// UnsafeCentralBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CentralBrokerServer will
// result in compilation errors.
type UnsafeCentralBrokerServer interface {
	mustEmbedUnimplementedCentralBrokerServer()
}

func RegisterCentralBrokerServer(s grpc.ServiceRegistrar, srv CentralBrokerServer) {
	// If the following call pancis, it indicates UnimplementedCentralBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CentralBroker_ServiceDesc, srv)
}

func _CentralBroker_UpdateFlightData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralBrokerServer).UpdateFlightData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralBroker_UpdateFlightData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralBrokerServer).UpdateFlightData(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralBroker_GetFlightData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralBrokerServer).GetFlightData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralBroker_GetFlightData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralBrokerServer).GetFlightData(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralBroker_BroadcastFlightStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlightStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralBrokerServer).BroadcastFlightStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralBroker_BroadcastFlightStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralBrokerServer).BroadcastFlightStatus(ctx, req.(*UpdateFlightStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralBroker_GetFlightStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralBrokerServer).GetFlightStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralBroker_GetFlightStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralBrokerServer).GetFlightStatus(ctx, req.(*FlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CentralBroker_ServiceDesc is the grpc.ServiceDesc for CentralBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CentralBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aerodist.CentralBroker",
	HandlerType: (*CentralBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateFlightData",
			Handler:    _CentralBroker_UpdateFlightData_Handler,
		},
		{
			MethodName: "GetFlightData",
			Handler:    _CentralBroker_GetFlightData_Handler,
		},
		{
			MethodName: "BroadcastFlightStatus",
			Handler:    _CentralBroker_BroadcastFlightStatus_Handler,
		},
		{
			MethodName: "GetFlightStatus",
			Handler:    _CentralBroker_GetFlightStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aerodist.proto",
}
