// proto/cyberday.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/cyberday.proto

package cyberday

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Solicitud de registro que incluye ID, Tipo y Direccion de la entidad
type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RegistrationRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *RegistrationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Resultado del registro
type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{2}
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// Mensaje de oferta que incluye todos los atributos necesarios
type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfertaId      string                 `protobuf:"bytes,1,opt,name=oferta_id,json=ofertaId,proto3" json:"oferta_id,omitempty"`
	Tienda        string                 `protobuf:"bytes,2,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Categoria     string                 `protobuf:"bytes,3,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Producto      string                 `protobuf:"bytes,4,opt,name=producto,proto3" json:"producto,omitempty"`
	Precio        int64                  `protobuf:"varint,5,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Fecha         string                 `protobuf:"bytes,7,opt,name=fecha,proto3" json:"fecha,omitempty"`
	Descuento     float32                `protobuf:"fixed32,8,opt,name=descuento,proto3" json:"descuento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_proto_cyberday_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{4}
}

func (x *Offer) GetOfertaId() string {
	if x != nil {
		return x.OfertaId
	}
	return ""
}

func (x *Offer) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Offer) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Offer) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Offer) GetPrecio() int64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Offer) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Offer) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *Offer) GetDescuento() float32 {
	if x != nil {
		return x.Descuento
	}
	return 0
}

// Mensaje que indica si la oferta se escribio exitosamente y tambien un indicador de si el broker sigue recibiendo ofertas
type OfferSubmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // True if W=2
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Termino       bool                   `protobuf:"varint,3,opt,name=termino,proto3" json:"termino,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferSubmissionResponse) Reset() {
	*x = OfferSubmissionResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferSubmissionResponse) ProtoMessage() {}

func (x *OfferSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferSubmissionResponse.ProtoReflect.Descriptor instead.
func (*OfferSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{5}
}

func (x *OfferSubmissionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *OfferSubmissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OfferSubmissionResponse) GetTermino() bool {
	if x != nil {
		return x.Termino
	}
	return false
}

// Mensaje que indica si una BD almacena correctamente una oferta
type StoreOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreOfferResponse) Reset() {
	*x = StoreOfferResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOfferResponse) ProtoMessage() {}

func (x *StoreOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOfferResponse.ProtoReflect.Descriptor instead.
func (*StoreOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{6}
}

func (x *StoreOfferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreOfferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Mensaje que solicita una resincronizacion incluyendo el id de la entidad
type RecoveryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingNodeId string                 `protobuf:"bytes,1,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecoveryRequest) Reset() {
	*x = RecoveryRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryRequest) ProtoMessage() {}

func (x *RecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryRequest.ProtoReflect.Descriptor instead.
func (*RecoveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{7}
}

func (x *RecoveryRequest) GetRequestingNodeId() string {
	if x != nil {
		return x.RequestingNodeId
	}
	return ""
}

// Mensaje que incluye el historial de ofertas
type RecoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*Offer               `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryResponse) Reset() {
	*x = RecoveryResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryResponse) ProtoMessage() {}

func (x *RecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryResponse.ProtoReflect.Descriptor instead.
func (*RecoveryResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{8}
}

func (x *RecoveryResponse) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

// Mensaje que indica si un consumidor recibio exitosamente una oferta
type ConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerResponse) Reset() {
	*x = ConsumerResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerResponse) ProtoMessage() {}

func (x *ConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerResponse.ProtoReflect.Descriptor instead.
func (*ConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Mensaje que notifica si es momento de terminar y forzar que no hayan masi caidas
type EndingNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fin           bool                   `protobuf:"varint,1,opt,name=fin,proto3" json:"fin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndingNotify) Reset() {
	*x = EndingNotify{}
	mi := &file_proto_cyberday_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndingNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndingNotify) ProtoMessage() {}

func (x *EndingNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndingNotify.ProtoReflect.Descriptor instead.
func (*EndingNotify) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{10}
}

func (x *EndingNotify) GetFin() bool {
	if x != nil {
		return x.Fin
	}
	return false
}

// Confirmaciones finalizacion por parte de BDs y Consumidores
type EndingConfirm struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Bdconfirm       bool                   `protobuf:"varint,1,opt,name=bdconfirm,proto3" json:"bdconfirm,omitempty"`
	Consumerconfirm bool                   `protobuf:"varint,2,opt,name=consumerconfirm,proto3" json:"consumerconfirm,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EndingConfirm) Reset() {
	*x = EndingConfirm{}
	mi := &file_proto_cyberday_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndingConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndingConfirm) ProtoMessage() {}

func (x *EndingConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndingConfirm.ProtoReflect.Descriptor instead.
func (*EndingConfirm) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{11}
}

func (x *EndingConfirm) GetBdconfirm() bool {
	if x != nil {
		return x.Bdconfirm
	}
	return false
}

func (x *EndingConfirm) GetConsumerconfirm() bool {
	if x != nil {
		return x.Consumerconfirm
	}
	return false
}

// Mensaje que envia el consumidor para solicitar el historico
type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{12}
}

func (x *HistoryRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

// Mensaje que incluye el historico filtrado
type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*Offer               `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{13}
}

func (x *HistoryResponse) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

// Mensaje que incluye el id y tipo de entidad que reporta la caida
type FailNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailNotify) Reset() {
	*x = FailNotify{}
	mi := &file_proto_cyberday_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailNotify) ProtoMessage() {}

func (x *FailNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailNotify.ProtoReflect.Descriptor instead.
func (*FailNotify) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{14}
}

func (x *FailNotify) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FailNotify) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Mensaje de acknowledgment sobre la caida
type FailACK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailACK) Reset() {
	*x = FailACK{}
	mi := &file_proto_cyberday_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailACK) ProtoMessage() {}

func (x *FailACK) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailACK.ProtoReflect.Descriptor instead.
func (*FailACK) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{15}
}

func (x *FailACK) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_proto_cyberday_proto protoreflect.FileDescriptor

const file_proto_cyberday_proto_rawDesc = "" +
	"\n" +
	"\x14proto/cyberday.proto\x12\bcyberday\"m\n" +
	"\x13RegistrationRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"J\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eConfirmRequest\"'\n" +
	"\x0fConfirmResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"\xd8\x01\n" +
	"\x05Offer\x12\x1b\n" +
	"\toferta_id\x18\x01 \x01(\tR\bofertaId\x12\x16\n" +
	"\x06tienda\x18\x02 \x01(\tR\x06tienda\x12\x1c\n" +
	"\tcategoria\x18\x03 \x01(\tR\tcategoria\x12\x1a\n" +
	"\bproducto\x18\x04 \x01(\tR\bproducto\x12\x16\n" +
	"\x06precio\x18\x05 \x01(\x03R\x06precio\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x14\n" +
	"\x05fecha\x18\a \x01(\tR\x05fecha\x12\x1c\n" +
	"\tdescuento\x18\b \x01(\x02R\tdescuento\"i\n" +
	"\x17OfferSubmissionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\atermino\x18\x03 \x01(\bR\atermino\"H\n" +
	"\x12StoreOfferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x0fRecoveryRequest\x12,\n" +
	"\x12requesting_node_id\x18\x01 \x01(\tR\x10requestingNodeId\";\n" +
	"\x10RecoveryResponse\x12'\n" +
	"\x06offers\x18\x01 \x03(\v2\x0f.cyberday.OfferR\x06offers\"F\n" +
	"\x10ConsumerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\fEndingNotify\x12\x10\n" +
	"\x03fin\x18\x01 \x01(\bR\x03fin\"W\n" +
	"\rEndingConfirm\x12\x1c\n" +
	"\tbdconfirm\x18\x01 \x01(\bR\tbdconfirm\x12(\n" +
	"\x0fconsumerconfirm\x18\x02 \x01(\bR\x0fconsumerconfirm\"1\n" +
	"\x0eHistoryRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\":\n" +
	"\x0fHistoryResponse\x12'\n" +
	"\x06offers\x18\x01 \x03(\v2\x0f.cyberday.OfferR\x06offers\"0\n" +
	"\n" +
	"FailNotify\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x1b\n" +
	"\aFailACK\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack2c\n" +
	"\x10EntityManagement\x12O\n" +
	"\x0eRegisterEntity\x12\x1d.cyberday.RegistrationRequest\x1a\x1e.cyberday.RegistrationResponse2V\n" +
	"\x0fConfirmarInicio\x12C\n" +
	"\fConfirmacion\x12\x18.cyberday.ConfirmRequest\x1a\x19.cyberday.ConfirmResponse2R\n" +
	"\x0fOfferSubmission\x12?\n" +
	"\tSendOffer\x12\x0f.cyberday.Offer\x1a!.cyberday.OfferSubmissionResponse2\x8f\x01\n" +
	"\x06DBNode\x12;\n" +
	"\n" +
	"StoreOffer\x12\x0f.cyberday.Offer\x1a\x1c.cyberday.StoreOfferResponse\x12H\n" +
	"\x0fGetOfferHistory\x12\x19.cyberday.RecoveryRequest\x1a\x1a.cyberday.RecoveryResponse2G\n" +
	"\bConsumer\x12;\n" +
	"\fReceiveOffer\x12\x0f.cyberday.Offer\x1a\x1a.cyberday.ConsumerResponse2W\n" +
	"\fFinalizacion\x12G\n" +
	"\x14InformarFinalizacion\x12\x16.cyberday.EndingNotify\x1a\x17.cyberday.EndingConfirm2U\n" +
	"\bRecovery\x12I\n" +
	"\x12GetFilteredHistory\x12\x18.cyberday.HistoryRequest\x1a\x19.cyberday.HistoryResponse2A\n" +
	"\x05Caida\x128\n" +
	"\rInformarCaida\x12\x14.cyberday.FailNotify\x1a\x11.cyberday.FailACKB\rZ\v./;cyberdayb\x06proto3"

var (
	file_proto_cyberday_proto_rawDescOnce sync.Once
	file_proto_cyberday_proto_rawDescData []byte
)

func file_proto_cyberday_proto_rawDescGZIP() []byte {
	file_proto_cyberday_proto_rawDescOnce.Do(func() {
		file_proto_cyberday_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cyberday_proto_rawDesc), len(file_proto_cyberday_proto_rawDesc)))
	})
	return file_proto_cyberday_proto_rawDescData
}

var file_proto_cyberday_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_cyberday_proto_goTypes = []any{
	(*RegistrationRequest)(nil),     // 0: cyberday.RegistrationRequest
	(*RegistrationResponse)(nil),    // 1: cyberday.RegistrationResponse
	(*ConfirmRequest)(nil),          // 2: cyberday.ConfirmRequest
	(*ConfirmResponse)(nil),         // 3: cyberday.ConfirmResponse
	(*Offer)(nil),                   // 4: cyberday.Offer
	(*OfferSubmissionResponse)(nil), // 5: cyberday.OfferSubmissionResponse
	(*StoreOfferResponse)(nil),      // 6: cyberday.StoreOfferResponse
	(*RecoveryRequest)(nil),         // 7: cyberday.RecoveryRequest
	(*RecoveryResponse)(nil),        // 8: cyberday.RecoveryResponse
	(*ConsumerResponse)(nil),        // 9: cyberday.ConsumerResponse
	(*EndingNotify)(nil),            // 10: cyberday.EndingNotify
	(*EndingConfirm)(nil),           // 11: cyberday.EndingConfirm
	(*HistoryRequest)(nil),          // 12: cyberday.HistoryRequest
	(*HistoryResponse)(nil),         // 13: cyberday.HistoryResponse
	(*FailNotify)(nil),              // 14: cyberday.FailNotify
	(*FailACK)(nil),                 // 15: cyberday.FailACK
}
var file_proto_cyberday_proto_depIdxs = []int32{
	4,  // 0: cyberday.RecoveryResponse.offers:type_name -> cyberday.Offer
	4,  // 1: cyberday.HistoryResponse.offers:type_name -> cyberday.Offer
	0,  // 2: cyberday.EntityManagement.RegisterEntity:input_type -> cyberday.RegistrationRequest
	2,  // 3: cyberday.ConfirmarInicio.Confirmacion:input_type -> cyberday.ConfirmRequest
	4,  // 4: cyberday.OfferSubmission.SendOffer:input_type -> cyberday.Offer
	4,  // 5: cyberday.DBNode.StoreOffer:input_type -> cyberday.Offer
	7,  // 6: cyberday.DBNode.GetOfferHistory:input_type -> cyberday.RecoveryRequest
	4,  // 7: cyberday.Consumer.ReceiveOffer:input_type -> cyberday.Offer
	10, // 8: cyberday.Finalizacion.InformarFinalizacion:input_type -> cyberday.EndingNotify
	12, // 9: cyberday.Recovery.GetFilteredHistory:input_type -> cyberday.HistoryRequest
	14, // 10: cyberday.Caida.InformarCaida:input_type -> cyberday.FailNotify
	1,  // 11: cyberday.EntityManagement.RegisterEntity:output_type -> cyberday.RegistrationResponse
	3,  // 12: cyberday.ConfirmarInicio.Confirmacion:output_type -> cyberday.ConfirmResponse
	5,  // 13: cyberday.OfferSubmission.SendOffer:output_type -> cyberday.OfferSubmissionResponse
	6,  // 14: cyberday.DBNode.StoreOffer:output_type -> cyberday.StoreOfferResponse
	8,  // 15: cyberday.DBNode.GetOfferHistory:output_type -> cyberday.RecoveryResponse
	9,  // 16: cyberday.Consumer.ReceiveOffer:output_type -> cyberday.ConsumerResponse
	11, // 17: cyberday.Finalizacion.InformarFinalizacion:output_type -> cyberday.EndingConfirm
	13, // 18: cyberday.Recovery.GetFilteredHistory:output_type -> cyberday.HistoryResponse
	15, // 19: cyberday.Caida.InformarCaida:output_type -> cyberday.FailACK
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cyberday_proto_init() }
func file_proto_cyberday_proto_init() {
	if File_proto_cyberday_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cyberday_proto_rawDesc), len(file_proto_cyberday_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   8,
		},
		GoTypes:           file_proto_cyberday_proto_goTypes,
		DependencyIndexes: file_proto_cyberday_proto_depIdxs,
		MessageInfos:      file_proto_cyberday_proto_msgTypes,
	}.Build()
	File_proto_cyberday_proto = out.File
	file_proto_cyberday_proto_goTypes = nil
	file_proto_cyberday_proto_depIdxs = nil
}
