// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/cyberday.proto

package cyberday

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntityManagement_RegisterEntity_FullMethodName = "/cyberday.EntityManagement/RegisterEntity"
)

// EntityManagementClient is the client API for EntityManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for all entities to register with the Broker (Fase 1)
type EntityManagementClient interface {
	RegisterEntity(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error)
}

type entityManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewEntityManagementClient(cc grpc.ClientConnInterface) EntityManagementClient {
	return &entityManagementClient{cc}
}

func (c *entityManagementClient) RegisterEntity(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, EntityManagement_RegisterEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntityManagementServer is the server API for EntityManagement service.
// All implementations must embed UnimplementedEntityManagementServer
// for forward compatibility.
//
// Service for all entities to register with the Broker (Fase 1)
type EntityManagementServer interface {
	RegisterEntity(context.Context, *RegistrationRequest) (*RegistrationResponse, error)
	mustEmbedUnimplementedEntityManagementServer()
}

// UnimplementedEntityManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntityManagementServer struct{}

func (UnimplementedEntityManagementServer) RegisterEntity(context.Context, *RegistrationRequest) (*RegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterEntity not implemented")
}
func (UnimplementedEntityManagementServer) mustEmbedUnimplementedEntityManagementServer() {}
func (UnimplementedEntityManagementServer) testEmbeddedByValue()                          {}

// UnsafeEntityManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntityManagementServer will
// result in compilation errors.
type UnsafeEntityManagementServer interface {
	mustEmbedUnimplementedEntityManagementServer()
}

func RegisterEntityManagementServer(s grpc.ServiceRegistrar, srv EntityManagementServer) {
	// If the following call pancis, it indicates UnimplementedEntityManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntityManagement_ServiceDesc, srv)
}

func _EntityManagement_RegisterEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityManagementServer).RegisterEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityManagement_RegisterEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityManagementServer).RegisterEntity(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntityManagement_ServiceDesc is the grpc.ServiceDesc for EntityManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntityManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyberday.EntityManagement",
	HandlerType: (*EntityManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEntity",
			Handler:    _EntityManagement_RegisterEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cyberday.proto",
}

const (
	OfferSubmission_SendOffer_FullMethodName = "/cyberday.OfferSubmission/SendOffer"
)

// OfferSubmissionClient is the client API for OfferSubmission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for Producers to send offers to the Broker (Fase 2)
type OfferSubmissionClient interface {
	SendOffer(ctx context.Context, in *Offer, opts ...grpc.CallOption) (*OfferSubmissionResponse, error)
}

type offerSubmissionClient struct {
	cc grpc.ClientConnInterface
}

func NewOfferSubmissionClient(cc grpc.ClientConnInterface) OfferSubmissionClient {
	return &offerSubmissionClient{cc}
}

func (c *offerSubmissionClient) SendOffer(ctx context.Context, in *Offer, opts ...grpc.CallOption) (*OfferSubmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferSubmissionResponse)
	err := c.cc.Invoke(ctx, OfferSubmission_SendOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfferSubmissionServer is the server API for OfferSubmission service.
// All implementations must embed UnimplementedOfferSubmissionServer
// for forward compatibility.
//
// Service for Producers to send offers to the Broker (Fase 2)
type OfferSubmissionServer interface {
	SendOffer(context.Context, *Offer) (*OfferSubmissionResponse, error)
	mustEmbedUnimplementedOfferSubmissionServer()
}

// UnimplementedOfferSubmissionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOfferSubmissionServer struct{}

func (UnimplementedOfferSubmissionServer) SendOffer(context.Context, *Offer) (*OfferSubmissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOffer not implemented")
}
func (UnimplementedOfferSubmissionServer) mustEmbedUnimplementedOfferSubmissionServer() {}
func (UnimplementedOfferSubmissionServer) testEmbeddedByValue()                         {}

// UnsafeOfferSubmissionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfferSubmissionServer will
// result in compilation errors.
type UnsafeOfferSubmissionServer interface {
	mustEmbedUnimplementedOfferSubmissionServer()
}

func RegisterOfferSubmissionServer(s grpc.ServiceRegistrar, srv OfferSubmissionServer) {
	// If the following call pancis, it indicates UnimplementedOfferSubmissionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OfferSubmission_ServiceDesc, srv)
}

func _OfferSubmission_SendOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Offer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferSubmissionServer).SendOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfferSubmission_SendOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferSubmissionServer).SendOffer(ctx, req.(*Offer))
	}
	return interceptor(ctx, in, info, handler)
}

// OfferSubmission_ServiceDesc is the grpc.ServiceDesc for OfferSubmission service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OfferSubmission_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyberday.OfferSubmission",
	HandlerType: (*OfferSubmissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOffer",
			Handler:    _OfferSubmission_SendOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cyberday.proto",
}

const (
	DBNode_StoreOffer_FullMethodName = "/cyberday.DBNode/StoreOffer"
)

// DBNodeClient is the client API for DBNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for the Broker to write data to the DB Nodes (Fase 3)
type DBNodeClient interface {
	StoreOffer(ctx context.Context, in *Offer, opts ...grpc.CallOption) (*StoreOfferResponse, error)
}

type dBNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewDBNodeClient(cc grpc.ClientConnInterface) DBNodeClient {
	return &dBNodeClient{cc}
}

func (c *dBNodeClient) StoreOffer(ctx context.Context, in *Offer, opts ...grpc.CallOption) (*StoreOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreOfferResponse)
	err := c.cc.Invoke(ctx, DBNode_StoreOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBNodeServer is the server API for DBNode service.
// All implementations must embed UnimplementedDBNodeServer
// for forward compatibility.
//
// Service for the Broker to write data to the DB Nodes (Fase 3)
type DBNodeServer interface {
	StoreOffer(context.Context, *Offer) (*StoreOfferResponse, error)
	mustEmbedUnimplementedDBNodeServer()
}

// UnimplementedDBNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBNodeServer struct{}

func (UnimplementedDBNodeServer) StoreOffer(context.Context, *Offer) (*StoreOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreOffer not implemented")
}
func (UnimplementedDBNodeServer) mustEmbedUnimplementedDBNodeServer() {}
func (UnimplementedDBNodeServer) testEmbeddedByValue()                {}

// UnsafeDBNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBNodeServer will
// result in compilation errors.
type UnsafeDBNodeServer interface {
	mustEmbedUnimplementedDBNodeServer()
}

func RegisterDBNodeServer(s grpc.ServiceRegistrar, srv DBNodeServer) {
	// If the following call pancis, it indicates UnimplementedDBNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBNode_ServiceDesc, srv)
}

func _DBNode_StoreOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Offer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBNodeServer).StoreOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBNode_StoreOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBNodeServer).StoreOffer(ctx, req.(*Offer))
	}
	return interceptor(ctx, in, info, handler)
}

// DBNode_ServiceDesc is the grpc.ServiceDesc for DBNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyberday.DBNode",
	HandlerType: (*DBNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreOffer",
			Handler:    _DBNode_StoreOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cyberday.proto",
}

const (
	Broker_PostOffer_FullMethodName = "/cyberday.Broker/PostOffer"
)

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 💡 AGREGADO: Servicio principal que implementa el Broker (incluye PostOffer).
type BrokerClient interface {
	PostOffer(ctx context.Context, in *Offer, opts ...grpc.CallOption) (*BrokerResponse, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) PostOffer(ctx context.Context, in *Offer, opts ...grpc.CallOption) (*BrokerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrokerResponse)
	err := c.cc.Invoke(ctx, Broker_PostOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility.
//
// 💡 AGREGADO: Servicio principal que implementa el Broker (incluye PostOffer).
type BrokerServer interface {
	PostOffer(context.Context, *Offer) (*BrokerResponse, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServer struct{}

func (UnimplementedBrokerServer) PostOffer(context.Context, *Offer) (*BrokerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostOffer not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}
func (UnimplementedBrokerServer) testEmbeddedByValue()                {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	// If the following call pancis, it indicates UnimplementedBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_PostOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Offer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).PostOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_PostOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).PostOffer(ctx, req.(*Offer))
	}
	return interceptor(ctx, in, info, handler)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyberday.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostOffer",
			Handler:    _Broker_PostOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cyberday.proto",
}

const (
	Consumer_ReceiveOffer_FullMethodName = "/cyberday.Consumer/ReceiveOffer"
)

// ConsumerClient is the client API for Consumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 💡 NUEVO: Service for the Broker to notify Consumers (Fase 4)
type ConsumerClient interface {
	ReceiveOffer(ctx context.Context, in *Offer, opts ...grpc.CallOption) (*ConsumerResponse, error)
}

type consumerClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerClient(cc grpc.ClientConnInterface) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) ReceiveOffer(ctx context.Context, in *Offer, opts ...grpc.CallOption) (*ConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumerResponse)
	err := c.cc.Invoke(ctx, Consumer_ReceiveOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServer is the server API for Consumer service.
// All implementations must embed UnimplementedConsumerServer
// for forward compatibility.
//
// 💡 NUEVO: Service for the Broker to notify Consumers (Fase 4)
type ConsumerServer interface {
	ReceiveOffer(context.Context, *Offer) (*ConsumerResponse, error)
	mustEmbedUnimplementedConsumerServer()
}

// UnimplementedConsumerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsumerServer struct{}

func (UnimplementedConsumerServer) ReceiveOffer(context.Context, *Offer) (*ConsumerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveOffer not implemented")
}
func (UnimplementedConsumerServer) mustEmbedUnimplementedConsumerServer() {}
func (UnimplementedConsumerServer) testEmbeddedByValue()                  {}

// UnsafeConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServer will
// result in compilation errors.
type UnsafeConsumerServer interface {
	mustEmbedUnimplementedConsumerServer()
}

func RegisterConsumerServer(s grpc.ServiceRegistrar, srv ConsumerServer) {
	// If the following call pancis, it indicates UnimplementedConsumerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Consumer_ServiceDesc, srv)
}

func _Consumer_ReceiveOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Offer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).ReceiveOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumer_ReceiveOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).ReceiveOffer(ctx, req.(*Offer))
	}
	return interceptor(ctx, in, info, handler)
}

// Consumer_ServiceDesc is the grpc.ServiceDesc for Consumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyberday.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveOffer",
			Handler:    _Consumer_ReceiveOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cyberday.proto",
}
