// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/cyberday.proto

package cyberday

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structure of an Offer (needed for all communication)
type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfertaId      string                 `protobuf:"bytes,1,opt,name=oferta_id,json=ofertaId,proto3" json:"oferta_id,omitempty"`
	Tienda        string                 `protobuf:"bytes,2,opt,name=tienda,proto3" json:"tienda,omitempty"`       // Riploy, Falabellox, Parisio
	Categoria     string                 `protobuf:"bytes,3,opt,name=categoria,proto3" json:"categoria,omitempty"` // E.g., Electronica, Moda, Hogar
	Producto      string                 `protobuf:"bytes,4,opt,name=producto,proto3" json:"producto,omitempty"`
	Precio        int64                  `protobuf:"varint,5,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Fecha         string                 `protobuf:"bytes,7,opt,name=fecha,proto3" json:"fecha,omitempty"` // Timestamp
	Descuento     float32                `protobuf:"fixed32,8,opt,name=descuento,proto3" json:"descuento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_proto_cyberday_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{0}
}

func (x *Offer) GetOfertaId() string {
	if x != nil {
		return x.OfertaId
	}
	return ""
}

func (x *Offer) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Offer) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Offer) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Offer) GetPrecio() int64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Offer) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Offer) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *Offer) GetDescuento() float32 {
	if x != nil {
		return x.Descuento
	}
	return 0
}

// Request message for any entity (Producer, DB Node, Consumer) to register
type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`       // Unique identifier (e.g., "Riploy", "DB1", "C-E1")
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // Type (e.g., "Producer", "DBNode", "Consumer")
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                         // The gRPC address where this entity can be reached
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RegistrationRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *RegistrationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Response from the Broker confirming or denying registration
type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Respuesta del Broker al Productor después de SendOffer
type OfferSubmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // True if W=2 was achieved
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferSubmissionResponse) Reset() {
	*x = OfferSubmissionResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferSubmissionResponse) ProtoMessage() {}

func (x *OfferSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferSubmissionResponse.ProtoReflect.Descriptor instead.
func (*OfferSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{3}
}

func (x *OfferSubmissionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *OfferSubmissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 💡 AGREGADO: Respuesta del Broker después de procesar la oferta (para PostOffer).
type BrokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerResponse) Reset() {
	*x = BrokerResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerResponse) ProtoMessage() {}

func (x *BrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerResponse.ProtoReflect.Descriptor instead.
func (*BrokerResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{4}
}

func (x *BrokerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BrokerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Response que el Nodo DB envía al Broker después de intentar guardar la oferta.
type StoreOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreOfferResponse) Reset() {
	*x = StoreOfferResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOfferResponse) ProtoMessage() {}

func (x *StoreOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOfferResponse.ProtoReflect.Descriptor instead.
func (*StoreOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{5}
}

func (x *StoreOfferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreOfferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 💡 NUEVO: Respuesta que el Consumidor envía al Broker después de recibir la oferta.
type ConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerResponse) Reset() {
	*x = ConsumerResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerResponse) ProtoMessage() {}

func (x *ConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerResponse.ProtoReflect.Descriptor instead.
func (*ConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_cyberday_proto protoreflect.FileDescriptor

const file_proto_cyberday_proto_rawDesc = "" +
	"\n" +
	"\x14proto/cyberday.proto\x12\bcyberday\"\xd8\x01\n" +
	"\x05Offer\x12\x1b\n" +
	"\toferta_id\x18\x01 \x01(\tR\bofertaId\x12\x16\n" +
	"\x06tienda\x18\x02 \x01(\tR\x06tienda\x12\x1c\n" +
	"\tcategoria\x18\x03 \x01(\tR\tcategoria\x12\x1a\n" +
	"\bproducto\x18\x04 \x01(\tR\bproducto\x12\x16\n" +
	"\x06precio\x18\x05 \x01(\x03R\x06precio\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x14\n" +
	"\x05fecha\x18\a \x01(\tR\x05fecha\x12\x1c\n" +
	"\tdescuento\x18\b \x01(\x02R\tdescuento\"m\n" +
	"\x13RegistrationRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"J\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x17OfferSubmissionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x0eBrokerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x12StoreOfferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x10ConsumerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2c\n" +
	"\x10EntityManagement\x12O\n" +
	"\x0eRegisterEntity\x12\x1d.cyberday.RegistrationRequest\x1a\x1e.cyberday.RegistrationResponse2R\n" +
	"\x0fOfferSubmission\x12?\n" +
	"\tSendOffer\x12\x0f.cyberday.Offer\x1a!.cyberday.OfferSubmissionResponse2E\n" +
	"\x06DBNode\x12;\n" +
	"\n" +
	"StoreOffer\x12\x0f.cyberday.Offer\x1a\x1c.cyberday.StoreOfferResponse2@\n" +
	"\x06Broker\x126\n" +
	"\tPostOffer\x12\x0f.cyberday.Offer\x1a\x18.cyberday.BrokerResponse2G\n" +
	"\bConsumer\x12;\n" +
	"\fReceiveOffer\x12\x0f.cyberday.Offer\x1a\x1a.cyberday.ConsumerResponseB\rZ\v./;cyberdayb\x06proto3"

var (
	file_proto_cyberday_proto_rawDescOnce sync.Once
	file_proto_cyberday_proto_rawDescData []byte
)

func file_proto_cyberday_proto_rawDescGZIP() []byte {
	file_proto_cyberday_proto_rawDescOnce.Do(func() {
		file_proto_cyberday_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cyberday_proto_rawDesc), len(file_proto_cyberday_proto_rawDesc)))
	})
	return file_proto_cyberday_proto_rawDescData
}

var file_proto_cyberday_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_cyberday_proto_goTypes = []any{
	(*Offer)(nil),                   // 0: cyberday.Offer
	(*RegistrationRequest)(nil),     // 1: cyberday.RegistrationRequest
	(*RegistrationResponse)(nil),    // 2: cyberday.RegistrationResponse
	(*OfferSubmissionResponse)(nil), // 3: cyberday.OfferSubmissionResponse
	(*BrokerResponse)(nil),          // 4: cyberday.BrokerResponse
	(*StoreOfferResponse)(nil),      // 5: cyberday.StoreOfferResponse
	(*ConsumerResponse)(nil),        // 6: cyberday.ConsumerResponse
}
var file_proto_cyberday_proto_depIdxs = []int32{
	1, // 0: cyberday.EntityManagement.RegisterEntity:input_type -> cyberday.RegistrationRequest
	0, // 1: cyberday.OfferSubmission.SendOffer:input_type -> cyberday.Offer
	0, // 2: cyberday.DBNode.StoreOffer:input_type -> cyberday.Offer
	0, // 3: cyberday.Broker.PostOffer:input_type -> cyberday.Offer
	0, // 4: cyberday.Consumer.ReceiveOffer:input_type -> cyberday.Offer
	2, // 5: cyberday.EntityManagement.RegisterEntity:output_type -> cyberday.RegistrationResponse
	3, // 6: cyberday.OfferSubmission.SendOffer:output_type -> cyberday.OfferSubmissionResponse
	5, // 7: cyberday.DBNode.StoreOffer:output_type -> cyberday.StoreOfferResponse
	4, // 8: cyberday.Broker.PostOffer:output_type -> cyberday.BrokerResponse
	6, // 9: cyberday.Consumer.ReceiveOffer:output_type -> cyberday.ConsumerResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cyberday_proto_init() }
func file_proto_cyberday_proto_init() {
	if File_proto_cyberday_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cyberday_proto_rawDesc), len(file_proto_cyberday_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_proto_cyberday_proto_goTypes,
		DependencyIndexes: file_proto_cyberday_proto_depIdxs,
		MessageInfos:      file_proto_cyberday_proto_msgTypes,
	}.Build()
	File_proto_cyberday_proto = out.File
	file_proto_cyberday_proto_goTypes = nil
	file_proto_cyberday_proto_depIdxs = nil
}
