// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/atraco.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Solicitud de oferta que enviara Michael a Lester
type SolicitudOferta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudOferta) Reset() {
	*x = SolicitudOferta{}
	mi := &file_proto_atraco_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudOferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudOferta) ProtoMessage() {}

func (x *SolicitudOferta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudOferta.ProtoReflect.Descriptor instead.
func (*SolicitudOferta) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{0}
}

// Oferta disponible que enviara Lester luego de recibir una solicitud
type OfertaDisponible struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Disponible           bool                   `protobuf:"varint,1,opt,name=disponible,proto3" json:"disponible,omitempty"`
	BotinInicial         int32                  `protobuf:"varint,2,opt,name=botin_inicial,json=botinInicial,proto3" json:"botin_inicial,omitempty"`
	ProbabilidadFranklin float32                `protobuf:"fixed32,3,opt,name=probabilidad_franklin,json=probabilidadFranklin,proto3" json:"probabilidad_franklin,omitempty"`
	ProbabilidadTrevor   float32                `protobuf:"fixed32,4,opt,name=probabilidad_trevor,json=probabilidadTrevor,proto3" json:"probabilidad_trevor,omitempty"`
	RiesgoPolicial       float32                `protobuf:"fixed32,5,opt,name=riesgo_policial,json=riesgoPolicial,proto3" json:"riesgo_policial,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OfertaDisponible) Reset() {
	*x = OfertaDisponible{}
	mi := &file_proto_atraco_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfertaDisponible) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfertaDisponible) ProtoMessage() {}

func (x *OfertaDisponible) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfertaDisponible.ProtoReflect.Descriptor instead.
func (*OfertaDisponible) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{1}
}

func (x *OfertaDisponible) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

func (x *OfertaDisponible) GetBotinInicial() int32 {
	if x != nil {
		return x.BotinInicial
	}
	return 0
}

func (x *OfertaDisponible) GetProbabilidadFranklin() float32 {
	if x != nil {
		return x.ProbabilidadFranklin
	}
	return 0
}

func (x *OfertaDisponible) GetProbabilidadTrevor() float32 {
	if x != nil {
		return x.ProbabilidadTrevor
	}
	return 0
}

func (x *OfertaDisponible) GetRiesgoPolicial() float32 {
	if x != nil {
		return x.RiesgoPolicial
	}
	return 0
}

// Michael informa a Lester acerca de la confirmación de la oferta que le envió
type ConfirmacionOferta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aceptada      bool                   `protobuf:"varint,1,opt,name=aceptada,proto3" json:"aceptada,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacionOferta) Reset() {
	*x = ConfirmacionOferta{}
	mi := &file_proto_atraco_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionOferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionOferta) ProtoMessage() {}

func (x *ConfirmacionOferta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionOferta.ProtoReflect.Descriptor instead.
func (*ConfirmacionOferta) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmacionOferta) GetAceptada() bool {
	if x != nil {
		return x.Aceptada
	}
	return false
}

// Lester envía ACK de la confirmación
type AckConfirmacionOferta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckConfirmacionOferta) Reset() {
	*x = AckConfirmacionOferta{}
	mi := &file_proto_atraco_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckConfirmacionOferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckConfirmacionOferta) ProtoMessage() {}

func (x *AckConfirmacionOferta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckConfirmacionOferta.ProtoReflect.Descriptor instead.
func (*AckConfirmacionOferta) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{3}
}

// Michael informa del monto total de la operación a Lester y le paga su correspondencia
type MontoPago struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Correspondencia int32                  `protobuf:"varint,1,opt,name=correspondencia,proto3" json:"correspondencia,omitempty"`
	Total           int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MontoPago) Reset() {
	*x = MontoPago{}
	mi := &file_proto_atraco_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MontoPago) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MontoPago) ProtoMessage() {}

func (x *MontoPago) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MontoPago.ProtoReflect.Descriptor instead.
func (*MontoPago) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{4}
}

func (x *MontoPago) GetCorrespondencia() int32 {
	if x != nil {
		return x.Correspondencia
	}
	return 0
}

func (x *MontoPago) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Lester confirma el pago y le responde a Michael
type ConfirmarPagoLester struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correcto      bool                   `protobuf:"varint,1,opt,name=correcto,proto3" json:"correcto,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmarPagoLester) Reset() {
	*x = ConfirmarPagoLester{}
	mi := &file_proto_atraco_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmarPagoLester) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmarPagoLester) ProtoMessage() {}

func (x *ConfirmarPagoLester) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmarPagoLester.ProtoReflect.Descriptor instead.
func (*ConfirmarPagoLester) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmarPagoLester) GetCorrecto() bool {
	if x != nil {
		return x.Correcto
	}
	return false
}

func (x *ConfirmarPagoLester) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Michael informa a Lester para iniciar el envío de notificaciones a Trevor/Franklin
type InicioNotifEstrellas struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Personaje      string                 `protobuf:"bytes,1,opt,name=personaje,proto3" json:"personaje,omitempty"`
	RiesgoPolicial float32                `protobuf:"fixed32,2,opt,name=riesgo_policial,json=riesgoPolicial,proto3" json:"riesgo_policial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InicioNotifEstrellas) Reset() {
	*x = InicioNotifEstrellas{}
	mi := &file_proto_atraco_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InicioNotifEstrellas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InicioNotifEstrellas) ProtoMessage() {}

func (x *InicioNotifEstrellas) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InicioNotifEstrellas.ProtoReflect.Descriptor instead.
func (*InicioNotifEstrellas) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{6}
}

func (x *InicioNotifEstrellas) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

func (x *InicioNotifEstrellas) GetRiesgoPolicial() float32 {
	if x != nil {
		return x.RiesgoPolicial
	}
	return 0
}

// Lester envía ACK de inicio de envío de notificaciones
type AckInicioNotif struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckInicioNotif) Reset() {
	*x = AckInicioNotif{}
	mi := &file_proto_atraco_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckInicioNotif) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckInicioNotif) ProtoMessage() {}

func (x *AckInicioNotif) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckInicioNotif.ProtoReflect.Descriptor instead.
func (*AckInicioNotif) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{7}
}

// Michael informa a Lester para detener el envío de notifiaciones a Trevor/Franklin
type DetenerNotifEstrellas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personaje     string                 `protobuf:"bytes,1,opt,name=personaje,proto3" json:"personaje,omitempty"`
	Exito         bool                   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetenerNotifEstrellas) Reset() {
	*x = DetenerNotifEstrellas{}
	mi := &file_proto_atraco_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetenerNotifEstrellas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetenerNotifEstrellas) ProtoMessage() {}

func (x *DetenerNotifEstrellas) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetenerNotifEstrellas.ProtoReflect.Descriptor instead.
func (*DetenerNotifEstrellas) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{8}
}

func (x *DetenerNotifEstrellas) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

func (x *DetenerNotifEstrellas) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

// Lester envía ACK de detención de envío de notificaciones
type AckDetenerNotif struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckDetenerNotif) Reset() {
	*x = AckDetenerNotif{}
	mi := &file_proto_atraco_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckDetenerNotif) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckDetenerNotif) ProtoMessage() {}

func (x *AckDetenerNotif) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckDetenerNotif.ProtoReflect.Descriptor instead.
func (*AckDetenerNotif) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{9}
}

var File_proto_atraco_proto protoreflect.FileDescriptor

const file_proto_atraco_proto_rawDesc = "" +
	"\n" +
	"\x12proto/atraco.proto\"\x11\n" +
	"\x0fSolicitudOferta\"\xe6\x01\n" +
	"\x10OfertaDisponible\x12\x1e\n" +
	"\n" +
	"disponible\x18\x01 \x01(\bR\n" +
	"disponible\x12#\n" +
	"\rbotin_inicial\x18\x02 \x01(\x05R\fbotinInicial\x123\n" +
	"\x15probabilidad_franklin\x18\x03 \x01(\x02R\x14probabilidadFranklin\x12/\n" +
	"\x13probabilidad_trevor\x18\x04 \x01(\x02R\x12probabilidadTrevor\x12'\n" +
	"\x0friesgo_policial\x18\x05 \x01(\x02R\x0eriesgoPolicial\"0\n" +
	"\x12ConfirmacionOferta\x12\x1a\n" +
	"\baceptada\x18\x01 \x01(\bR\baceptada\"\x17\n" +
	"\x15AckConfirmacionOferta\"K\n" +
	"\tMontoPago\x12(\n" +
	"\x0fcorrespondencia\x18\x01 \x01(\x05R\x0fcorrespondencia\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"K\n" +
	"\x13ConfirmarPagoLester\x12\x1a\n" +
	"\bcorrecto\x18\x01 \x01(\bR\bcorrecto\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"]\n" +
	"\x14InicioNotifEstrellas\x12\x1c\n" +
	"\tpersonaje\x18\x01 \x01(\tR\tpersonaje\x12'\n" +
	"\x0friesgo_policial\x18\x02 \x01(\x02R\x0eriesgoPolicial\"\x10\n" +
	"\x0eAckInicioNotif\"K\n" +
	"\x15DetenerNotifEstrellas\x12\x1c\n" +
	"\tpersonaje\x18\x01 \x01(\tR\tpersonaje\x12\x14\n" +
	"\x05exito\x18\x02 \x01(\bR\x05exito\"\x11\n" +
	"\x0fAckDetenerNotif2\xcd\x02\n" +
	"\rMichaelLester\x125\n" +
	"\x0eEntregarOferta\x12\x10.SolicitudOferta\x1a\x11.OfertaDisponible\x12>\n" +
	"\x0fConfirmarOferta\x12\x13.ConfirmacionOferta\x1a\x16.AckConfirmacionOferta\x12/\n" +
	"\vPagarLester\x12\n" +
	".MontoPago\x1a\x14.ConfirmarPagoLester\x12H\n" +
	"\x1eIniciarNotificacionesEstrellas\x12\x15.InicioNotifEstrellas\x1a\x0f.AckInicioNotif\x12J\n" +
	"\x1eDetenerNotificacionesEstrellas\x12\x16.DetenerNotifEstrellas\x1a\x10.AckDetenerNotifB\tZ\a./protob\x06proto3"

var (
	file_proto_atraco_proto_rawDescOnce sync.Once
	file_proto_atraco_proto_rawDescData []byte
)

func file_proto_atraco_proto_rawDescGZIP() []byte {
	file_proto_atraco_proto_rawDescOnce.Do(func() {
		file_proto_atraco_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_atraco_proto_rawDesc), len(file_proto_atraco_proto_rawDesc)))
	})
	return file_proto_atraco_proto_rawDescData
}

var file_proto_atraco_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_atraco_proto_goTypes = []any{
	(*SolicitudOferta)(nil),       // 0: SolicitudOferta
	(*OfertaDisponible)(nil),      // 1: OfertaDisponible
	(*ConfirmacionOferta)(nil),    // 2: ConfirmacionOferta
	(*AckConfirmacionOferta)(nil), // 3: AckConfirmacionOferta
	(*MontoPago)(nil),             // 4: MontoPago
	(*ConfirmarPagoLester)(nil),   // 5: ConfirmarPagoLester
	(*InicioNotifEstrellas)(nil),  // 6: InicioNotifEstrellas
	(*AckInicioNotif)(nil),        // 7: AckInicioNotif
	(*DetenerNotifEstrellas)(nil), // 8: DetenerNotifEstrellas
	(*AckDetenerNotif)(nil),       // 9: AckDetenerNotif
}
var file_proto_atraco_proto_depIdxs = []int32{
	0, // 0: MichaelLester.EntregarOferta:input_type -> SolicitudOferta
	2, // 1: MichaelLester.ConfirmarOferta:input_type -> ConfirmacionOferta
	4, // 2: MichaelLester.PagarLester:input_type -> MontoPago
	6, // 3: MichaelLester.IniciarNotificacionesEstrellas:input_type -> InicioNotifEstrellas
	8, // 4: MichaelLester.DetenerNotificacionesEstrellas:input_type -> DetenerNotifEstrellas
	1, // 5: MichaelLester.EntregarOferta:output_type -> OfertaDisponible
	3, // 6: MichaelLester.ConfirmarOferta:output_type -> AckConfirmacionOferta
	5, // 7: MichaelLester.PagarLester:output_type -> ConfirmarPagoLester
	7, // 8: MichaelLester.IniciarNotificacionesEstrellas:output_type -> AckInicioNotif
	9, // 9: MichaelLester.DetenerNotificacionesEstrellas:output_type -> AckDetenerNotif
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_atraco_proto_init() }
func file_proto_atraco_proto_init() {
	if File_proto_atraco_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_atraco_proto_rawDesc), len(file_proto_atraco_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_atraco_proto_goTypes,
		DependencyIndexes: file_proto_atraco_proto_depIdxs,
		MessageInfos:      file_proto_atraco_proto_msgTypes,
	}.Build()
	File_proto_atraco_proto = out.File
	file_proto_atraco_proto_goTypes = nil
	file_proto_atraco_proto_depIdxs = nil
}
