// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/atraco.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Solicitud de oferta que enviara Michael
type SolicitudOferta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudOferta) Reset() {
	*x = SolicitudOferta{}
	mi := &file_proto_atraco_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudOferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudOferta) ProtoMessage() {}

func (x *SolicitudOferta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudOferta.ProtoReflect.Descriptor instead.
func (*SolicitudOferta) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{0}
}

// Oferta disponible que enviara Lester luego de recibir una solicitud, incluye el botin inicial, la probabilidad de exito de Trevor y Franklin y el Riesgo policial
type OfertaDisponible struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Disponible           bool                   `protobuf:"varint,1,opt,name=disponible,proto3" json:"disponible,omitempty"`
	BotinInicial         int32                  `protobuf:"varint,2,opt,name=botin_inicial,json=botinInicial,proto3" json:"botin_inicial,omitempty"`
	ProbabilidadFranklin float32                `protobuf:"fixed32,3,opt,name=probabilidad_franklin,json=probabilidadFranklin,proto3" json:"probabilidad_franklin,omitempty"`
	ProbabilidadTrevor   float32                `protobuf:"fixed32,4,opt,name=probabilidad_trevor,json=probabilidadTrevor,proto3" json:"probabilidad_trevor,omitempty"`
	RiesgoPolicial       float32                `protobuf:"fixed32,5,opt,name=riesgo_policial,json=riesgoPolicial,proto3" json:"riesgo_policial,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OfertaDisponible) Reset() {
	*x = OfertaDisponible{}
	mi := &file_proto_atraco_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfertaDisponible) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfertaDisponible) ProtoMessage() {}

func (x *OfertaDisponible) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfertaDisponible.ProtoReflect.Descriptor instead.
func (*OfertaDisponible) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{1}
}

func (x *OfertaDisponible) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

func (x *OfertaDisponible) GetBotinInicial() int32 {
	if x != nil {
		return x.BotinInicial
	}
	return 0
}

func (x *OfertaDisponible) GetProbabilidadFranklin() float32 {
	if x != nil {
		return x.ProbabilidadFranklin
	}
	return 0
}

func (x *OfertaDisponible) GetProbabilidadTrevor() float32 {
	if x != nil {
		return x.ProbabilidadTrevor
	}
	return 0
}

func (x *OfertaDisponible) GetRiesgoPolicial() float32 {
	if x != nil {
		return x.RiesgoPolicial
	}
	return 0
}

type Confirmacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aceptada      bool                   `protobuf:"varint,1,opt,name=aceptada,proto3" json:"aceptada,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirmacion) Reset() {
	*x = Confirmacion{}
	mi := &file_proto_atraco_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmacion) ProtoMessage() {}

func (x *Confirmacion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmacion.ProtoReflect.Descriptor instead.
func (*Confirmacion) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{2}
}

func (x *Confirmacion) GetAceptada() bool {
	if x != nil {
		return x.Aceptada
	}
	return false
}

type AckConfirmacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckConfirmacion) Reset() {
	*x = AckConfirmacion{}
	mi := &file_proto_atraco_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckConfirmacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckConfirmacion) ProtoMessage() {}

func (x *AckConfirmacion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckConfirmacion.ProtoReflect.Descriptor instead.
func (*AckConfirmacion) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{3}
}

// Informe de trabajo que enviara Michael que incluye la probabilidad de exito del trabajador
type InformarDistraccion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProbabilidadExito float32                `protobuf:"fixed32,1,opt,name=probabilidad_exito,json=probabilidadExito,proto3" json:"probabilidad_exito,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InformarDistraccion) Reset() {
	*x = InformarDistraccion{}
	mi := &file_proto_atraco_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformarDistraccion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformarDistraccion) ProtoMessage() {}

func (x *InformarDistraccion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformarDistraccion.ProtoReflect.Descriptor instead.
func (*InformarDistraccion) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{4}
}

func (x *InformarDistraccion) GetProbabilidadExito() float32 {
	if x != nil {
		return x.ProbabilidadExito
	}
	return 0
}

// Resultado de la mision enviado por Franklin o Trevor que incluye un indicador sobre si la mision fue un exito o fracaso
type ResultadoDistraccion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Motivo        string                 `protobuf:"bytes,2,opt,name=motivo,proto3" json:"motivo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoDistraccion) Reset() {
	*x = ResultadoDistraccion{}
	mi := &file_proto_atraco_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoDistraccion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoDistraccion) ProtoMessage() {}

func (x *ResultadoDistraccion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoDistraccion.ProtoReflect.Descriptor instead.
func (*ResultadoDistraccion) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{5}
}

func (x *ResultadoDistraccion) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ResultadoDistraccion) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

type InformarGolpe struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProbabilidadExito float32                `protobuf:"fixed32,1,opt,name=probabilidad_exito,json=probabilidadExito,proto3" json:"probabilidad_exito,omitempty"`
	Botin             int32                  `protobuf:"varint,2,opt,name=botin,proto3" json:"botin,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InformarGolpe) Reset() {
	*x = InformarGolpe{}
	mi := &file_proto_atraco_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformarGolpe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformarGolpe) ProtoMessage() {}

func (x *InformarGolpe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformarGolpe.ProtoReflect.Descriptor instead.
func (*InformarGolpe) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{6}
}

func (x *InformarGolpe) GetProbabilidadExito() float32 {
	if x != nil {
		return x.ProbabilidadExito
	}
	return 0
}

func (x *InformarGolpe) GetBotin() int32 {
	if x != nil {
		return x.Botin
	}
	return 0
}

// Resultado de la mision enviado por Franklin o Trevor que incluye un indicador sobre si la mision fue un exito o fracaso
type ResultadoGolpe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Botin         int32                  `protobuf:"varint,2,opt,name=botin,proto3" json:"botin,omitempty"`
	Motivo        string                 `protobuf:"bytes,3,opt,name=motivo,proto3" json:"motivo,omitempty"`
	BotinExtra    int32                  `protobuf:"varint,4,opt,name=botin_extra,json=botinExtra,proto3" json:"botin_extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoGolpe) Reset() {
	*x = ResultadoGolpe{}
	mi := &file_proto_atraco_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoGolpe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoGolpe) ProtoMessage() {}

func (x *ResultadoGolpe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoGolpe.ProtoReflect.Descriptor instead.
func (*ResultadoGolpe) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{7}
}

func (x *ResultadoGolpe) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ResultadoGolpe) GetBotin() int32 {
	if x != nil {
		return x.Botin
	}
	return 0
}

func (x *ResultadoGolpe) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

func (x *ResultadoGolpe) GetBotinExtra() int32 {
	if x != nil {
		return x.BotinExtra
	}
	return 0
}

type Monto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Correspondencia int32                  `protobuf:"varint,1,opt,name=correspondencia,proto3" json:"correspondencia,omitempty"`
	Total           int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Monto) Reset() {
	*x = Monto{}
	mi := &file_proto_atraco_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monto) ProtoMessage() {}

func (x *Monto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monto.ProtoReflect.Descriptor instead.
func (*Monto) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{8}
}

func (x *Monto) GetCorrespondencia() int32 {
	if x != nil {
		return x.Correspondencia
	}
	return 0
}

func (x *Monto) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ConfirmarPago struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correcto      bool                   `protobuf:"varint,1,opt,name=correcto,proto3" json:"correcto,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmarPago) Reset() {
	*x = ConfirmarPago{}
	mi := &file_proto_atraco_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmarPago) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmarPago) ProtoMessage() {}

func (x *ConfirmarPago) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmarPago.ProtoReflect.Descriptor instead.
func (*ConfirmarPago) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmarPago) GetCorrecto() bool {
	if x != nil {
		return x.Correcto
	}
	return false
}

func (x *ConfirmarPago) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_proto_atraco_proto protoreflect.FileDescriptor

const file_proto_atraco_proto_rawDesc = "" +
	"\n" +
	"\x12proto/atraco.proto\"\x11\n" +
	"\x0fSolicitudOferta\"\xe6\x01\n" +
	"\x10OfertaDisponible\x12\x1e\n" +
	"\n" +
	"disponible\x18\x01 \x01(\bR\n" +
	"disponible\x12#\n" +
	"\rbotin_inicial\x18\x02 \x01(\x05R\fbotinInicial\x123\n" +
	"\x15probabilidad_franklin\x18\x03 \x01(\x02R\x14probabilidadFranklin\x12/\n" +
	"\x13probabilidad_trevor\x18\x04 \x01(\x02R\x12probabilidadTrevor\x12'\n" +
	"\x0friesgo_policial\x18\x05 \x01(\x02R\x0eriesgoPolicial\"*\n" +
	"\fConfirmacion\x12\x1a\n" +
	"\baceptada\x18\x01 \x01(\bR\baceptada\"\x11\n" +
	"\x0fAckConfirmacion\"D\n" +
	"\x13InformarDistraccion\x12-\n" +
	"\x12probabilidad_exito\x18\x01 \x01(\x02R\x11probabilidadExito\"D\n" +
	"\x14ResultadoDistraccion\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x16\n" +
	"\x06motivo\x18\x02 \x01(\tR\x06motivo\"T\n" +
	"\rInformarGolpe\x12-\n" +
	"\x12probabilidad_exito\x18\x01 \x01(\x02R\x11probabilidadExito\x12\x14\n" +
	"\x05botin\x18\x02 \x01(\x05R\x05botin\"u\n" +
	"\x0eResultadoGolpe\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x14\n" +
	"\x05botin\x18\x02 \x01(\x05R\x05botin\x12\x16\n" +
	"\x06motivo\x18\x03 \x01(\tR\x06motivo\x12\x1f\n" +
	"\vbotin_extra\x18\x04 \x01(\x05R\n" +
	"botinExtra\"G\n" +
	"\x05Monto\x12(\n" +
	"\x0fcorrespondencia\x18\x01 \x01(\x05R\x0fcorrespondencia\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"E\n" +
	"\rConfirmarPago\x12\x1a\n" +
	"\bcorrecto\x18\x01 \x01(\bR\bcorrecto\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje2\x9b\x01\n" +
	"\rMichaelLester\x125\n" +
	"\x0eEntregarOferta\x12\x10.SolicitudOferta\x1a\x11.OfertaDisponible\x122\n" +
	"\x0fConfirmarOferta\x12\r.Confirmacion\x1a\x10.AckConfirmacion\x12\x1f\n" +
	"\x05Pagar\x12\x06.Monto\x1a\x0e.ConfirmarPago2\xc0\x01\n" +
	"\x15MichaelTrevorFranklin\x12H\n" +
	"\x19InformarEstadoSegundaFase\x12\x14.InformarDistraccion\x1a\x15.ResultadoDistraccion\x12<\n" +
	"\x19InformarEstadoTerceraFase\x12\x0e.InformarGolpe\x1a\x0f.ResultadoGolpe\x12\x1f\n" +
	"\x05Pagar\x12\x06.Monto\x1a\x0e.ConfirmarPagoB\bZ\x06/protob\x06proto3"

var (
	file_proto_atraco_proto_rawDescOnce sync.Once
	file_proto_atraco_proto_rawDescData []byte
)

func file_proto_atraco_proto_rawDescGZIP() []byte {
	file_proto_atraco_proto_rawDescOnce.Do(func() {
		file_proto_atraco_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_atraco_proto_rawDesc), len(file_proto_atraco_proto_rawDesc)))
	})
	return file_proto_atraco_proto_rawDescData
}

var file_proto_atraco_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_atraco_proto_goTypes = []any{
	(*SolicitudOferta)(nil),      // 0: SolicitudOferta
	(*OfertaDisponible)(nil),     // 1: OfertaDisponible
	(*Confirmacion)(nil),         // 2: Confirmacion
	(*AckConfirmacion)(nil),      // 3: AckConfirmacion
	(*InformarDistraccion)(nil),  // 4: InformarDistraccion
	(*ResultadoDistraccion)(nil), // 5: ResultadoDistraccion
	(*InformarGolpe)(nil),        // 6: InformarGolpe
	(*ResultadoGolpe)(nil),       // 7: ResultadoGolpe
	(*Monto)(nil),                // 8: Monto
	(*ConfirmarPago)(nil),        // 9: ConfirmarPago
}
var file_proto_atraco_proto_depIdxs = []int32{
	0, // 0: MichaelLester.EntregarOferta:input_type -> SolicitudOferta
	2, // 1: MichaelLester.ConfirmarOferta:input_type -> Confirmacion
	8, // 2: MichaelLester.Pagar:input_type -> Monto
	4, // 3: MichaelTrevorFranklin.InformarEstadoSegundaFase:input_type -> InformarDistraccion
	6, // 4: MichaelTrevorFranklin.InformarEstadoTerceraFase:input_type -> InformarGolpe
	8, // 5: MichaelTrevorFranklin.Pagar:input_type -> Monto
	1, // 6: MichaelLester.EntregarOferta:output_type -> OfertaDisponible
	3, // 7: MichaelLester.ConfirmarOferta:output_type -> AckConfirmacion
	9, // 8: MichaelLester.Pagar:output_type -> ConfirmarPago
	5, // 9: MichaelTrevorFranklin.InformarEstadoSegundaFase:output_type -> ResultadoDistraccion
	7, // 10: MichaelTrevorFranklin.InformarEstadoTerceraFase:output_type -> ResultadoGolpe
	9, // 11: MichaelTrevorFranklin.Pagar:output_type -> ConfirmarPago
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_atraco_proto_init() }
func file_proto_atraco_proto_init() {
	if File_proto_atraco_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_atraco_proto_rawDesc), len(file_proto_atraco_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_atraco_proto_goTypes,
		DependencyIndexes: file_proto_atraco_proto_depIdxs,
		MessageInfos:      file_proto_atraco_proto_msgTypes,
	}.Build()
	File_proto_atraco_proto = out.File
	file_proto_atraco_proto_goTypes = nil
	file_proto_atraco_proto_depIdxs = nil
}
