// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/atraco.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Solicitud de oferta que enviara Michael
type SolicitudOferta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudOferta) Reset() {
	*x = SolicitudOferta{}
	mi := &file_proto_atraco_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudOferta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudOferta) ProtoMessage() {}

func (x *SolicitudOferta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudOferta.ProtoReflect.Descriptor instead.
func (*SolicitudOferta) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{0}
}

// Oferta disponible que enviara Lester luego de recibir una solicitud, incluye el botin inicial, la probabilidad de exito de Trevor y Franklin y el Riesgo policial
type OfertaDisponible struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Disponible           bool                   `protobuf:"varint,1,opt,name=disponible,proto3" json:"disponible,omitempty"`
	BotinInicial         int32                  `protobuf:"varint,2,opt,name=botin_inicial,json=botinInicial,proto3" json:"botin_inicial,omitempty"`
	ProbabilidadFranklin float32                `protobuf:"fixed32,3,opt,name=probabilidad_franklin,json=probabilidadFranklin,proto3" json:"probabilidad_franklin,omitempty"`
	ProbabilidadTrevor   float32                `protobuf:"fixed32,4,opt,name=probabilidad_trevor,json=probabilidadTrevor,proto3" json:"probabilidad_trevor,omitempty"`
	RiesgoPolicial       float32                `protobuf:"fixed32,5,opt,name=riesgo_policial,json=riesgoPolicial,proto3" json:"riesgo_policial,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OfertaDisponible) Reset() {
	*x = OfertaDisponible{}
	mi := &file_proto_atraco_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfertaDisponible) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfertaDisponible) ProtoMessage() {}

func (x *OfertaDisponible) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfertaDisponible.ProtoReflect.Descriptor instead.
func (*OfertaDisponible) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{1}
}

func (x *OfertaDisponible) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

func (x *OfertaDisponible) GetBotinInicial() int32 {
	if x != nil {
		return x.BotinInicial
	}
	return 0
}

func (x *OfertaDisponible) GetProbabilidadFranklin() float32 {
	if x != nil {
		return x.ProbabilidadFranklin
	}
	return 0
}

func (x *OfertaDisponible) GetProbabilidadTrevor() float32 {
	if x != nil {
		return x.ProbabilidadTrevor
	}
	return 0
}

func (x *OfertaDisponible) GetRiesgoPolicial() float32 {
	if x != nil {
		return x.RiesgoPolicial
	}
	return 0
}

type Confirmacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aceptada      bool                   `protobuf:"varint,1,opt,name=aceptada,proto3" json:"aceptada,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirmacion) Reset() {
	*x = Confirmacion{}
	mi := &file_proto_atraco_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmacion) ProtoMessage() {}

func (x *Confirmacion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmacion.ProtoReflect.Descriptor instead.
func (*Confirmacion) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{2}
}

func (x *Confirmacion) GetAceptada() bool {
	if x != nil {
		return x.Aceptada
	}
	return false
}

type AckConfirmacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckConfirmacion) Reset() {
	*x = AckConfirmacion{}
	mi := &file_proto_atraco_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckConfirmacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckConfirmacion) ProtoMessage() {}

func (x *AckConfirmacion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckConfirmacion.ProtoReflect.Descriptor instead.
func (*AckConfirmacion) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{3}
}

// Informe de trabajo que enviara Michael que incluye la probabilidad de exito del trabajador
type InformarTrabajo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProbabilidadExito float32                `protobuf:"fixed32,2,opt,name=probabilidad_exito,json=probabilidadExito,proto3" json:"probabilidad_exito,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InformarTrabajo) Reset() {
	*x = InformarTrabajo{}
	mi := &file_proto_atraco_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformarTrabajo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformarTrabajo) ProtoMessage() {}

func (x *InformarTrabajo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformarTrabajo.ProtoReflect.Descriptor instead.
func (*InformarTrabajo) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{4}
}

func (x *InformarTrabajo) GetProbabilidadExito() float32 {
	if x != nil {
		return x.ProbabilidadExito
	}
	return 0
}

// Resultado de la mision enviado por Franklin o Trevor que incluye un indicador sobre si la mision fue un exito o fracaso
type Resultado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resultado) Reset() {
	*x = Resultado{}
	mi := &file_proto_atraco_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resultado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resultado) ProtoMessage() {}

func (x *Resultado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atraco_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resultado.ProtoReflect.Descriptor instead.
func (*Resultado) Descriptor() ([]byte, []int) {
	return file_proto_atraco_proto_rawDescGZIP(), []int{5}
}

func (x *Resultado) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

var File_proto_atraco_proto protoreflect.FileDescriptor

const file_proto_atraco_proto_rawDesc = "" +
	"\n" +
	"\x12proto/atraco.proto\"\x11\n" +
	"\x0fSolicitudOferta\"\xe6\x01\n" +
	"\x10OfertaDisponible\x12\x1e\n" +
	"\n" +
	"disponible\x18\x01 \x01(\bR\n" +
	"disponible\x12#\n" +
	"\rbotin_inicial\x18\x02 \x01(\x05R\fbotinInicial\x123\n" +
	"\x15probabilidad_franklin\x18\x03 \x01(\x02R\x14probabilidadFranklin\x12/\n" +
	"\x13probabilidad_trevor\x18\x04 \x01(\x02R\x12probabilidadTrevor\x12'\n" +
	"\x0friesgo_policial\x18\x05 \x01(\x02R\x0eriesgoPolicial\"*\n" +
	"\fConfirmacion\x12\x1a\n" +
	"\baceptada\x18\x01 \x01(\bR\baceptada\"\x11\n" +
	"\x0fAckConfirmacion\"@\n" +
	"\x0fInformarTrabajo\x12-\n" +
	"\x12probabilidad_exito\x18\x02 \x01(\x02R\x11probabilidadExito\"!\n" +
	"\tResultado\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito2s\n" +
	"\x06Oferta\x125\n" +
	"\x0eEntregarOferta\x12\x10.SolicitudOferta\x1a\x11.OfertaDisponible\x122\n" +
	"\x0fConfirmarOferta\x12\r.Confirmacion\x1a\x10.AckConfirmacion2H\n" +
	"\vSegundaFase\x129\n" +
	"\x19InformarEstadoSegundaFase\x12\x10.InformarTrabajo\x1a\n" +
	".ResultadoB\bZ\x06/protob\x06proto3"

var (
	file_proto_atraco_proto_rawDescOnce sync.Once
	file_proto_atraco_proto_rawDescData []byte
)

func file_proto_atraco_proto_rawDescGZIP() []byte {
	file_proto_atraco_proto_rawDescOnce.Do(func() {
		file_proto_atraco_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_atraco_proto_rawDesc), len(file_proto_atraco_proto_rawDesc)))
	})
	return file_proto_atraco_proto_rawDescData
}

var file_proto_atraco_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_atraco_proto_goTypes = []any{
	(*SolicitudOferta)(nil),  // 0: SolicitudOferta
	(*OfertaDisponible)(nil), // 1: OfertaDisponible
	(*Confirmacion)(nil),     // 2: Confirmacion
	(*AckConfirmacion)(nil),  // 3: AckConfirmacion
	(*InformarTrabajo)(nil),  // 4: InformarTrabajo
	(*Resultado)(nil),        // 5: Resultado
}
var file_proto_atraco_proto_depIdxs = []int32{
	0, // 0: Oferta.EntregarOferta:input_type -> SolicitudOferta
	2, // 1: Oferta.ConfirmarOferta:input_type -> Confirmacion
	4, // 2: SegundaFase.InformarEstadoSegundaFase:input_type -> InformarTrabajo
	1, // 3: Oferta.EntregarOferta:output_type -> OfertaDisponible
	3, // 4: Oferta.ConfirmarOferta:output_type -> AckConfirmacion
	5, // 5: SegundaFase.InformarEstadoSegundaFase:output_type -> Resultado
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_atraco_proto_init() }
func file_proto_atraco_proto_init() {
	if File_proto_atraco_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_atraco_proto_rawDesc), len(file_proto_atraco_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_atraco_proto_goTypes,
		DependencyIndexes: file_proto_atraco_proto_depIdxs,
		MessageInfos:      file_proto_atraco_proto_msgTypes,
	}.Build()
	File_proto_atraco_proto = out.File
	file_proto_atraco_proto_goTypes = nil
	file_proto_atraco_proto_depIdxs = nil
}
