services:
  # --- BROKER CENTRAL ---
  broker:
    build: 
      context: .
      dockerfile: Broker/Dockerfile
    container_name: Broker
    ports:
      - "50095:50095"
    volumes:
      - ./Broker/:/app/Broker  
   

  # --- NODOS DE BASE DE DATOS ---
  db1:
    build:
      context: .
      dockerfile: Databases/Dockerfile
    container_name: DB1
    command: ["./dbnodo", "-id=DB1", "-port=:50061"]
    ports:
      - "50061:50061"

  db2:
    build:
      context: .
      dockerfile: Databases/Dockerfile
    container_name: DB2
    command: ["./dbnodo", "-id=DB2", "-port=:50062"]
    ports:
      - "50062:50062"

  db3:
    build:
      context: .
      dockerfile: Databases/Dockerfile
    container_name: DB3
    command: ["./dbnodo", "-id=DB3", "-port=:50063"]
    ports:
      - "50063:50063"

  # --- PRODUCTORES ---
  riploy:
    build:
      context: .
      dockerfile: Productores/Dockerfile
    container_name: Riploy
    command: ["./productor", "-id=Riploy", "-port=:50052"]
    ports:
      - "50052:50052"

  falabellox:
    build:
      context: .
      dockerfile: Productores/Dockerfile
    container_name: Falabellox
    command: ["./productor", "-id=Falabellox", "-port=:50053"]
    ports:
      - "50053:50053"

  parisio:
    build:
      context: .
      dockerfile: Productores/Dockerfile
    container_name: Parisio
    command: ["./productor", "-id=Parisio", "-port=:50054"]
    ports:
      - "50054:50054"
  
  consumer-group-1:
    build:
      context: .
      dockerfile: Consumidores/Dockerfile
    container_name: Consumer-Group-1
    command: /bin/sh -c "mkdir -p /app/output && rm -rf /app/output/* && exec /app/start-group1.sh"
    ports:
      - "50071:50071"
      - "50072:50072" 
      - "50073:50073"
      - "50074:50074"
    volumes:
    - ./csv_clientes:/app/output 

  consumer-group-2:
    build:
      context: .
      dockerfile: Consumidores/Dockerfile
    container_name: Consumer-Group-2
    command: /bin/sh -c "mkdir -p /app/output && rm -rf /app/output/* && exec /app/start-group2.sh"
    ports:
      - "50075:50075"
      - "50076:50076"
      - "50077:50077"
      - "50078:50078"
    volumes:
    - ./csv_clientes:/app/output 

  consumer-group-3:
    build:
      context: .
      dockerfile: Consumidores/Dockerfile
    container_name: Consumer-Group-3
    command: /bin/sh -c "mkdir -p /app/output && rm -rf /app/output/* && exec /app/start-group3.sh"
    ports:
      - "50079:50079"
      - "50080:50080"
      - "50081:50081"
      - "50082:50082"
    volumes:
    - ./csv_clientes:/app/output 

