version: '3.8'

services:
  # --- Datanodes (Servicios de Consistencia Eventual) ---

  datanode1:
    build:
      context: .
      dockerfile: Dockerfile  
      args:
        TARGET_DIR: datanode
    command: ["/app/datanode_bin", "-id=DN-1", "-port=:50061"]
    ports:
      - "50061:50061" 
    networks:
      - aerodist-net
  
  datanode2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET_DIR: datanode
    command: ["/app/datanode_bin", "-id=DN-2", "-port=:50062"]
    ports:
      - "50062:50062"
    networks:
      - aerodist-net
  
  datanode3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET_DIR: datanode
    command: ["/app/datanode_bin", "-id=DN-3", "-port=:50063"]
    ports:      
      - "50063:50063"
    networks:
      - aerodist-net

  # --- Broker Central ---
  broker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET_DIR: broker
    volumes:
      # Mapea la carpeta local './data' a la carpeta '/app/data' dentro del contenedor
      # Asegúrate de que tu archivo CSV esté en ./data/flight_updates.csv
      - ./data:/app/data
    environment:
      - LISTEN_PORT=:50052
      # Direcciones de los Datanodes. Usamos el nombre del servicio Docker (datanodeX)
      - DATANODE_ADDRS=datanode1:50061,datanode2:50062,datanode3:50063 
    networks:
      - aerodist-net
    depends_on:
      - datanode1
      - datanode2
      - datanode3

  # --- Coordinador (Gateway RYW) ---
  # Nuevo Servicio: Coordinador
  coordinator:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Asumimos que el código de clientes.go está en un subdirectorio llamado 'observadores'
        TARGET_DIR: coordinator
    container_name: coordinator-1
    ports:
      - "50055:50055"
    environment:
      - LISTEN_PORT=:50055
    depends_on:
      - broker
      - datanode1
    networks:
      - aerodist-net

  # --- Cliente RYW (Para Pruebas) ---
  # Nuevo Cliente: Check-in (Read Your Writes)
  client_ryw:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
          # Asumimos que el código de clientes.go está en un subdirectorio llamado 'observadores'
          TARGET_DIR: client_ryw
    container_name: client_ryw-1
    environment:
      - COORDINATOR_ADDR=coordinator:50055
    depends_on:
      - coordinator
    networks:
      - aerodist-net

  # --- CLIENTE MONOTONIC READS (Pasajero Observador) ---
  client_mr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Asumimos que el código de clientes.go está en un subdirectorio llamado 'observadores'
        TARGET_DIR: client_mr
    volumes:
      # Necesita el CSV para leer la lista de IDs de vuelos
      - ./data:/app/data 
    environment:
      # Dirección del Central Broker. Usamos el nombre del servicio Docker (broker:puerto)
      - BROKER_ADDR=broker:50052 
      - CSV_FILE_PATH=/app/data/flight_updates.csv
    networks:
      - aerodist-net
    depends_on:
      - broker # Depende de que el Broker esté corriendo
    # El cliente correrá en un bucle infinito para consultar periódicamente.
    # No usamos 'restart: "no"' para que se quede corriendo.

networks:
  aerodist-net:
    driver: bridge
